{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [],
   "source": [
    "df1 = pd.read_csv('topclusters0101.txt')\n",
    "df2 = pd.read_csv('topclusters0201.txt')\n",
    "df3 = pd.read_csv('topclusters0101_0105.txt',sep=\"\\t\")\n",
    "\n",
    "pd.set_option('display.max_colwidth', -1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>cluster_size</th>\n",
       "      <th>pattern</th>\n",
       "      <th>mean_similarity</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <td>0</td>\n",
       "      <td>79615</td>\n",
       "      <td>err: Communication error on send, err: [SE][][] httpg:/:/srm/: CGSI-gSOAP running on reports Error reading token data header: Connection</td>\n",
       "      <td>0.94</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>1</td>\n",
       "      <td>60088</td>\n",
       "      <td>Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: []</td>\n",
       "      <td>0.99</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>2</td>\n",
       "      <td>29732</td>\n",
       "      <td>Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [4003] Authentication to:1094 failed; all protocols have been tried.</td>\n",
       "      <td>0.90</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>3</td>\n",
       "      <td>29279</td>\n",
       "      <td>: the server responded with an error 500 error in: No such file or directory 500-A system call failed: No such file or directory 500 End.</td>\n",
       "      <td>0.98</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>4</td>\n",
       "      <td>26537</td>\n",
       "      <td>Destination file exists and overwrite is not enabled</td>\n",
       "      <td>1.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>5</td>\n",
       "      <td>24407</td>\n",
       "      <td>｟*｠: Unable to connect to:2811｟*｠: System error in connect: Connection｟*｠: A system call failed: Connection</td>\n",
       "      <td>0.89</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>6</td>\n",
       "      <td>19802</td>\n",
       "      <td>Error reported from srm_ifce : 2 [SE][Ls][SRM_INVALID_PATH] No such file or directory</td>\n",
       "      <td>0.99</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>7</td>\n",
       "      <td>18333</td>\n",
       "      <td>end-of-file was reached｟*｠: An end of file occurred</td>\n",
       "      <td>1.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>8</td>\n",
       "      <td>18207</td>\n",
       "      <td>[gfalt_copy_file][perform_copy][gfal_xrootd_3rd_copy][gfal_xrootd_3rd_copy_bulk] Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: []</td>\n",
       "      <td>0.99</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>9</td>\n",
       "      <td>17760</td>\n",
       "      <td>SOURCE SRM_GET_TURL error on the turl request : [SE][][SRM_FILE_UNAVAILABLE] File is.</td>\n",
       "      <td>1.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>10</td>\n",
       "      <td>16797</td>\n",
       "      <td>TRANSFER Transfer canceled because the gsiftp performance marker timeout of 360 seconds has been exceeded, or all performance markers during that period indicated zero bytes transferred</td>\n",
       "      <td>1.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>11</td>\n",
       "      <td>15907</td>\n",
       "      <td>Protocol not supported or path/url invalid: root:/:1094/dpm//home/atlas/atlasscratchdisk/rucio/tests///</td>\n",
       "      <td>0.68</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>12</td>\n",
       "      <td>15783</td>\n",
       "      <td>err: Communication error on send, err: [SE][][] httpg:/:/srm/managerv2: CGSI-gSOAP running on reports could not open connection to:</td>\n",
       "      <td>0.84</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>13</td>\n",
       "      <td>14821</td>\n",
       "      <td>Protocol not supported or path/url invalid: root:/:1094//atlas/atlasscratchdisk/rucio/tests///</td>\n",
       "      <td>0.66</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>14</td>\n",
       "      <td>14629</td>\n",
       "      <td>Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [] Unable to //////;</td>\n",
       "      <td>0.61</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>15</td>\n",
       "      <td>14581</td>\n",
       "      <td>Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Unable to open /dpm/nipne.ro/home/atlas/atlasscratchdisk/rucio/tests//; no delegated credentials for tpc</td>\n",
       "      <td>0.86</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>16</td>\n",
       "      <td>13091</td>\n",
       "      <td>: the server responded with an error 421 Service busy: Connection limit exceeded. Please try again later. Closing control connection.</td>\n",
       "      <td>0.98</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>17</td>\n",
       "      <td>12665</td>\n",
       "      <td>: the server responded with an error 530 530-globus_xio: Authentication Error 530-OpenSSL Error: s3_srvr.c:: in library: SSL routines, function: certificate 530-globus_gsi_callback_module: Could not verify credential 530-globus_gsi_callback_module: The certificate: with subject: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=/CN=/CN=/CN=/CN=</td>\n",
       "      <td>0.96</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>18</td>\n",
       "      <td>12409</td>\n",
       "      <td>Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Unable to create /pnfs/usatlas.bnl.gov/atlasscratchdisk/rucio/tests///; permission denied</td>\n",
       "      <td>0.85</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>19</td>\n",
       "      <td>11878</td>\n",
       "      <td>Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Access denied: /pnfs/triumf.ca/data/atlas/atlasscratchdisk/rucio/tests//</td>\n",
       "      <td>0.84</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    cluster_size  \\\n",
       "0   79615          \n",
       "1   60088          \n",
       "2   29732          \n",
       "3   29279          \n",
       "4   26537          \n",
       "5   24407          \n",
       "6   19802          \n",
       "7   18333          \n",
       "8   18207          \n",
       "9   17760          \n",
       "10  16797          \n",
       "11  15907          \n",
       "12  15783          \n",
       "13  14821          \n",
       "14  14629          \n",
       "15  14581          \n",
       "16  13091          \n",
       "17  12665          \n",
       "18  12409          \n",
       "19  11878          \n",
       "\n",
       "                                                                                                                                                                                                                                                                                                                                                 pattern  \\\n",
       "0   err: Communication error on send, err: [SE][][] httpg:/:/srm/: CGSI-gSOAP running on reports Error reading token data header: Connection                                                                                                                                                                                                               \n",
       "1   Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: []                                                                                                                                                                                                                                                                           \n",
       "2   Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [4003] Authentication to:1094 failed; all protocols have been tried.                                                                                                                                                                                                         \n",
       "3   : the server responded with an error 500 error in: No such file or directory 500-A system call failed: No such file or directory 500 End.                                                                                                                                                                                                              \n",
       "4   Destination file exists and overwrite is not enabled                                                                                                                                                                                                                                                                                                   \n",
       "5   ｟*｠: Unable to connect to:2811｟*｠: System error in connect: Connection｟*｠: A system call failed: Connection                                                                                                                                                                                                                                            \n",
       "6   Error reported from srm_ifce : 2 [SE][Ls][SRM_INVALID_PATH] No such file or directory                                                                                                                                                                                                                                                                  \n",
       "7   end-of-file was reached｟*｠: An end of file occurred                                                                                                                                                                                                                                                                                                    \n",
       "8   [gfalt_copy_file][perform_copy][gfal_xrootd_3rd_copy][gfal_xrootd_3rd_copy_bulk] Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: []                                                                                                                                                                                          \n",
       "9   SOURCE SRM_GET_TURL error on the turl request : [SE][][SRM_FILE_UNAVAILABLE] File is.                                                                                                                                                                                                                                                                  \n",
       "10  TRANSFER Transfer canceled because the gsiftp performance marker timeout of 360 seconds has been exceeded, or all performance markers during that period indicated zero bytes transferred                                                                                                                                                              \n",
       "11  Protocol not supported or path/url invalid: root:/:1094/dpm//home/atlas/atlasscratchdisk/rucio/tests///                                                                                                                                                                                                                                                \n",
       "12  err: Communication error on send, err: [SE][][] httpg:/:/srm/managerv2: CGSI-gSOAP running on reports could not open connection to:                                                                                                                                                                                                                    \n",
       "13  Protocol not supported or path/url invalid: root:/:1094//atlas/atlasscratchdisk/rucio/tests///                                                                                                                                                                                                                                                         \n",
       "14  Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [] Unable to //////;                                                                                                                                                                                                                                                         \n",
       "15  Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Unable to open /dpm/nipne.ro/home/atlas/atlasscratchdisk/rucio/tests//; no delegated credentials for tpc                                                                                                                                                              \n",
       "16  : the server responded with an error 421 Service busy: Connection limit exceeded. Please try again later. Closing control connection.                                                                                                                                                                                                                  \n",
       "17  : the server responded with an error 530 530-globus_xio: Authentication Error 530-OpenSSL Error: s3_srvr.c:: in library: SSL routines, function: certificate 530-globus_gsi_callback_module: Could not verify credential 530-globus_gsi_callback_module: The certificate: with subject: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=/CN=/CN=/CN=/CN=   \n",
       "18  Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Unable to create /pnfs/usatlas.bnl.gov/atlasscratchdisk/rucio/tests///; permission denied                                                                                                                                                                             \n",
       "19  Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Access denied: /pnfs/triumf.ca/data/atlas/atlasscratchdisk/rucio/tests//                                                                                                                                                                                              \n",
       "\n",
       "    mean_similarity  \n",
       "0   0.94             \n",
       "1   0.99             \n",
       "2   0.90             \n",
       "3   0.98             \n",
       "4   1.00             \n",
       "5   0.89             \n",
       "6   0.99             \n",
       "7   1.00             \n",
       "8   0.99             \n",
       "9   1.00             \n",
       "10  1.00             \n",
       "11  0.68             \n",
       "12  0.84             \n",
       "13  0.66             \n",
       "14  0.61             \n",
       "15  0.86             \n",
       "16  0.98             \n",
       "17  0.96             \n",
       "18  0.85             \n",
       "19  0.84             "
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#top20 clusters from 2020 01 01\n",
    "df1[['cluster_size', 'pattern', 'mean_similarity']]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>cluster_size</th>\n",
       "      <th>pattern</th>\n",
       "      <th>mean_similarity</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <td>0</td>\n",
       "      <td>81144</td>\n",
       "      <td>TRANSFER Transfer canceled because the gsiftp performance marker timeout of 360 seconds has been exceeded, or all performance markers during that period indicated zero bytes transferred</td>\n",
       "      <td>1.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>1</td>\n",
       "      <td>71853</td>\n",
       "      <td>TRANSFER globus_ftp_client: the server responded with an error All pools are full</td>\n",
       "      <td>1.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>2</td>\n",
       "      <td>65714</td>\n",
       "      <td>TRANSFER globus_ftp_client: the server responded with an error 451 General problem: Failed to connect [2001::::]::</td>\n",
       "      <td>0.97</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>3</td>\n",
       "      <td>52799</td>\n",
       "      <td>Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: []</td>\n",
       "      <td>0.99</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>4</td>\n",
       "      <td>45834</td>\n",
       "      <td>TRANSFER｟*｠ out</td>\n",
       "      <td>1.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>5</td>\n",
       "      <td>43650</td>\n",
       "      <td>TRANSFER globus_ftp_client: the server responded with an error 500 Command failed. : open/create : [ERROR] Server responded with an error: [3021] Unable to get quota space - quota not defined or exhausted /eos///</td>\n",
       "      <td>0.90</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>6</td>\n",
       "      <td>41683</td>\n",
       "      <td>Protocol not supported or path/url invalid: root:/:1094//atlasscratchdisk/rucio/tests//</td>\n",
       "      <td>0.62</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>7</td>\n",
       "      <td>34127</td>\n",
       "      <td>err: Communication error on send, err: [SE][][] httpg:/:/srm/managerv2: CGSI-gSOAP running on reports Error reading token data header: Connection</td>\n",
       "      <td>0.85</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>8</td>\n",
       "      <td>31416</td>\n",
       "      <td>TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. :: Unable to connect to:: 500-globus_xio: System error in connect: Connection 500-globus_xio: A system call failed: Connection 500 End.</td>\n",
       "      <td>0.97</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>9</td>\n",
       "      <td>26379</td>\n",
       "      <td>: the server responded with an error 421 Service busy: Connection limit exceeded. Please try again later. Closing control connection.</td>\n",
       "      <td>0.99</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>10</td>\n",
       "      <td>24693</td>\n",
       "      <td>SOURCE CHECKSUM globus_ftp_client: the server responded with an error 500 error:｟*｠ denied</td>\n",
       "      <td>1.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>11</td>\n",
       "      <td>22993</td>\n",
       "      <td>end-of-file was reached globus_xio: An end of file occurred</td>\n",
       "      <td>0.99</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>12</td>\n",
       "      <td>22580</td>\n",
       "      <td>Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [4003] Authentication to:1094 failed; all protocols have been tried.</td>\n",
       "      <td>0.88</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>13</td>\n",
       "      <td>22348</td>\n",
       "      <td>Destination file exists and overwrite is not enabled</td>\n",
       "      <td>1.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>14</td>\n",
       "      <td>22233</td>\n",
       "      <td>: Unable to connect to: globus_xio: System error in connect: Connection globus_xio: A system call failed: Connection</td>\n",
       "      <td>0.91</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>15</td>\n",
       "      <td>20669</td>\n",
       "      <td>reported from srm_ifce : 2 [SE][Ls][SRM_INVALID_PATH] No such file or directory</td>\n",
       "      <td>0.99</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>16</td>\n",
       "      <td>19241</td>\n",
       "      <td>Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Unable to create //atlasscratchdisk/rucio/tests//; permission denied</td>\n",
       "      <td>0.82</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>17</td>\n",
       "      <td>17282</td>\n",
       "      <td>[gfalt_copy_file][perform_copy][gfal_xrootd_3rd_copy][gfal_xrootd_3rd_copy_bulk] Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: []</td>\n",
       "      <td>0.99</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>18</td>\n",
       "      <td>13755</td>\n",
       "      <td>Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Unable to open /dpm/nipne.ro/home/atlas/atlasscratchdisk/rucio/tests//; no delegated credentials for tpc</td>\n",
       "      <td>0.86</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>19</td>\n",
       "      <td>10753</td>\n",
       "      <td>Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3012] sync - TPC open failed for src_url=root:/:///rucio///?fst.readahead=true</td>\n",
       "      <td>0.75</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    cluster_size  \\\n",
       "0   81144          \n",
       "1   71853          \n",
       "2   65714          \n",
       "3   52799          \n",
       "4   45834          \n",
       "5   43650          \n",
       "6   41683          \n",
       "7   34127          \n",
       "8   31416          \n",
       "9   26379          \n",
       "10  24693          \n",
       "11  22993          \n",
       "12  22580          \n",
       "13  22348          \n",
       "14  22233          \n",
       "15  20669          \n",
       "16  19241          \n",
       "17  17282          \n",
       "18  13755          \n",
       "19  10753          \n",
       "\n",
       "                                                                                                                                                                                                                           pattern  \\\n",
       "0   TRANSFER Transfer canceled because the gsiftp performance marker timeout of 360 seconds has been exceeded, or all performance markers during that period indicated zero bytes transferred                                        \n",
       "1   TRANSFER globus_ftp_client: the server responded with an error All pools are full                                                                                                                                                \n",
       "2   TRANSFER globus_ftp_client: the server responded with an error 451 General problem: Failed to connect [2001::::]::                                                                                                               \n",
       "3   Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: []                                                                                                                                                     \n",
       "4   TRANSFER｟*｠ out                                                                                                                                                                                                                  \n",
       "5   TRANSFER globus_ftp_client: the server responded with an error 500 Command failed. : open/create : [ERROR] Server responded with an error: [3021] Unable to get quota space - quota not defined or exhausted /eos///             \n",
       "6   Protocol not supported or path/url invalid: root:/:1094//atlasscratchdisk/rucio/tests//                                                                                                                                          \n",
       "7   err: Communication error on send, err: [SE][][] httpg:/:/srm/managerv2: CGSI-gSOAP running on reports Error reading token data header: Connection                                                                                \n",
       "8   TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. :: Unable to connect to:: 500-globus_xio: System error in connect: Connection 500-globus_xio: A system call failed: Connection 500 End.   \n",
       "9   : the server responded with an error 421 Service busy: Connection limit exceeded. Please try again later. Closing control connection.                                                                                            \n",
       "10  SOURCE CHECKSUM globus_ftp_client: the server responded with an error 500 error:｟*｠ denied                                                                                                                                       \n",
       "11  end-of-file was reached globus_xio: An end of file occurred                                                                                                                                                                      \n",
       "12  Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [4003] Authentication to:1094 failed; all protocols have been tried.                                                                                   \n",
       "13  Destination file exists and overwrite is not enabled                                                                                                                                                                             \n",
       "14  : Unable to connect to: globus_xio: System error in connect: Connection globus_xio: A system call failed: Connection                                                                                                             \n",
       "15  reported from srm_ifce : 2 [SE][Ls][SRM_INVALID_PATH] No such file or directory                                                                                                                                                  \n",
       "16  Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Unable to create //atlasscratchdisk/rucio/tests//; permission denied                                                                            \n",
       "17  [gfalt_copy_file][perform_copy][gfal_xrootd_3rd_copy][gfal_xrootd_3rd_copy_bulk] Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: []                                                                    \n",
       "18  Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Unable to open /dpm/nipne.ro/home/atlas/atlasscratchdisk/rucio/tests//; no delegated credentials for tpc                                        \n",
       "19  Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3012] sync - TPC open failed for src_url=root:/:///rucio///?fst.readahead=true                                                                        \n",
       "\n",
       "    mean_similarity  \n",
       "0   1.00             \n",
       "1   1.00             \n",
       "2   0.97             \n",
       "3   0.99             \n",
       "4   1.00             \n",
       "5   0.90             \n",
       "6   0.62             \n",
       "7   0.85             \n",
       "8   0.97             \n",
       "9   0.99             \n",
       "10  1.00             \n",
       "11  0.99             \n",
       "12  0.88             \n",
       "13  1.00             \n",
       "14  0.91             \n",
       "15  0.99             \n",
       "16  0.82             \n",
       "17  0.99             \n",
       "18  0.86             \n",
       "19  0.75             "
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#top20 clusters from 2020 02 01\n",
    "df2[['cluster_size', 'pattern', 'mean_similarity']]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>cluster_size</th>\n",
       "      <th>pattern</th>\n",
       "      <th>mean_similarity</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <td>0</td>\n",
       "      <td>376259</td>\n",
       "      <td>: the server responded with an error 421 Service busy: Connection limit exceeded. Please try again later. Closing control connection.</td>\n",
       "      <td>0.91</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>1</td>\n",
       "      <td>287026</td>\n",
       "      <td>Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: []</td>\n",
       "      <td>0.99</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>2</td>\n",
       "      <td>261651</td>\n",
       "      <td>err: Communication error on send, err: [SE][][] httpg:/:/srm/: CGSI-gSOAP running on reports:</td>\n",
       "      <td>0.80</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>3</td>\n",
       "      <td>223600</td>\n",
       "      <td>Protocol not supported or path/url invalid: root:/:1094//atlasscratchdisk/rucio/tests///</td>\n",
       "      <td>0.62</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>4</td>\n",
       "      <td>145034</td>\n",
       "      <td>SOURCE SRM_GET_TURL error on the turl request : [SE][][SRM_FILE_UNAVAILABLE] File is.</td>\n",
       "      <td>0.93</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>5</td>\n",
       "      <td>140256</td>\n",
       "      <td>Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [4003] Authentication to:1094 failed; all protocols have been tried.</td>\n",
       "      <td>0.88</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>6</td>\n",
       "      <td>135286</td>\n",
       "      <td>: the server responded with an error 530 530-globus_xio: Authentication Error 530-OpenSSL Error: s3_srvr.c:: in library: SSL routines, function: certificate 530-globus_gsi_callback_module: Could not verify credential 530-globus_gsi_callback_module: The certificate: with subject: /=/=/OU=/CN=/CN=/CN=/CN=</td>\n",
       "      <td>0.83</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>7</td>\n",
       "      <td>126516</td>\n",
       "      <td>Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Unable to //////; permission denied</td>\n",
       "      <td>0.81</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>8</td>\n",
       "      <td>98165</td>\n",
       "      <td>reported from srm_ifce : 2 [SE][Ls][SRM_INVALID_PATH] No such file or directory</td>\n",
       "      <td>0.99</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>9</td>\n",
       "      <td>93597</td>\n",
       "      <td>Destination file exists and overwrite is not enabled</td>\n",
       "      <td>1.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>10</td>\n",
       "      <td>89908</td>\n",
       "      <td>TRANSFER Transfer canceled because the gsiftp performance marker timeout of 360 seconds has been exceeded, or all performance markers during that period indicated zero bytes transferred</td>\n",
       "      <td>1.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>11</td>\n",
       "      <td>89444</td>\n",
       "      <td>[gfalt_copy_file][perform_copy][gfal_xrootd_3rd_copy][gfal_xrootd_3rd_copy_bulk] Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: []</td>\n",
       "      <td>0.99</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>12</td>\n",
       "      <td>71375</td>\n",
       "      <td>Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Unable to /dpm//home/atlas/atlasscratchdisk/rucio/tests//;</td>\n",
       "      <td>0.86</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>13</td>\n",
       "      <td>67316</td>\n",
       "      <td>DESTINATION error on the turl request : [SE][][SRM_FAILURE] Unable to store the request in StoRM DB</td>\n",
       "      <td>0.90</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>14</td>\n",
       "      <td>65701</td>\n",
       "      <td>end-of-file was reached globus_xio: An end of file occurred</td>\n",
       "      <td>0.98</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>15</td>\n",
       "      <td>63085</td>\n",
       "      <td>error on the turl request : [SE][][] &lt;none&gt;</td>\n",
       "      <td>0.92</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>16</td>\n",
       "      <td>59578</td>\n",
       "      <td>TRANSFER｟*｠ timed out</td>\n",
       "      <td>1.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>17</td>\n",
       "      <td>57784</td>\n",
       "      <td>DESTINATION OVERWRITE Connection timed out</td>\n",
       "      <td>1.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>18</td>\n",
       "      <td>57462</td>\n",
       "      <td>: Unable to connect to: globus_xio: System error in connect: Connection globus_xio: A system call failed: Connection</td>\n",
       "      <td>0.87</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>19</td>\n",
       "      <td>55054</td>\n",
       "      <td>Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3012] sync - TPC open failed for src_url=root:/://atlasscratchdisk/rucio/tests///?fst.readahead=true</td>\n",
       "      <td>0.75</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    cluster_size  \\\n",
       "0   376259         \n",
       "1   287026         \n",
       "2   261651         \n",
       "3   223600         \n",
       "4   145034         \n",
       "5   140256         \n",
       "6   135286         \n",
       "7   126516         \n",
       "8   98165          \n",
       "9   93597          \n",
       "10  89908          \n",
       "11  89444          \n",
       "12  71375          \n",
       "13  67316          \n",
       "14  65701          \n",
       "15  63085          \n",
       "16  59578          \n",
       "17  57784          \n",
       "18  57462          \n",
       "19  55054          \n",
       "\n",
       "                                                                                                                                                                                                                                                                                                             pattern  \\\n",
       "0   : the server responded with an error 421 Service busy: Connection limit exceeded. Please try again later. Closing control connection.                                                                                                                                                                              \n",
       "1   Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: []                                                                                                                                                                                                                                       \n",
       "2   err: Communication error on send, err: [SE][][] httpg:/:/srm/: CGSI-gSOAP running on reports:                                                                                                                                                                                                                      \n",
       "3   Protocol not supported or path/url invalid: root:/:1094//atlasscratchdisk/rucio/tests///                                                                                                                                                                                                                           \n",
       "4   SOURCE SRM_GET_TURL error on the turl request : [SE][][SRM_FILE_UNAVAILABLE] File is.                                                                                                                                                                                                                              \n",
       "5   Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [4003] Authentication to:1094 failed; all protocols have been tried.                                                                                                                                                                     \n",
       "6   : the server responded with an error 530 530-globus_xio: Authentication Error 530-OpenSSL Error: s3_srvr.c:: in library: SSL routines, function: certificate 530-globus_gsi_callback_module: Could not verify credential 530-globus_gsi_callback_module: The certificate: with subject: /=/=/OU=/CN=/CN=/CN=/CN=   \n",
       "7   Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Unable to //////; permission denied                                                                                                                                                                                               \n",
       "8   reported from srm_ifce : 2 [SE][Ls][SRM_INVALID_PATH] No such file or directory                                                                                                                                                                                                                                    \n",
       "9   Destination file exists and overwrite is not enabled                                                                                                                                                                                                                                                               \n",
       "10  TRANSFER Transfer canceled because the gsiftp performance marker timeout of 360 seconds has been exceeded, or all performance markers during that period indicated zero bytes transferred                                                                                                                          \n",
       "11  [gfalt_copy_file][perform_copy][gfal_xrootd_3rd_copy][gfal_xrootd_3rd_copy_bulk] Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: []                                                                                                                                                      \n",
       "12  Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Unable to /dpm//home/atlas/atlasscratchdisk/rucio/tests//;                                                                                                                                                                        \n",
       "13  DESTINATION error on the turl request : [SE][][SRM_FAILURE] Unable to store the request in StoRM DB                                                                                                                                                                                                                \n",
       "14  end-of-file was reached globus_xio: An end of file occurred                                                                                                                                                                                                                                                        \n",
       "15  error on the turl request : [SE][][] <none>                                                                                                                                                                                                                                                                        \n",
       "16  TRANSFER｟*｠ timed out                                                                                                                                                                                                                                                                                              \n",
       "17  DESTINATION OVERWRITE Connection timed out                                                                                                                                                                                                                                                                         \n",
       "18  : Unable to connect to: globus_xio: System error in connect: Connection globus_xio: A system call failed: Connection                                                                                                                                                                                               \n",
       "19  Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3012] sync - TPC open failed for src_url=root:/://atlasscratchdisk/rucio/tests///?fst.readahead=true                                                                                                                                    \n",
       "\n",
       "    mean_similarity  \n",
       "0   0.91             \n",
       "1   0.99             \n",
       "2   0.80             \n",
       "3   0.62             \n",
       "4   0.93             \n",
       "5   0.88             \n",
       "6   0.83             \n",
       "7   0.81             \n",
       "8   0.99             \n",
       "9   1.00             \n",
       "10  1.00             \n",
       "11  0.99             \n",
       "12  0.86             \n",
       "13  0.90             \n",
       "14  0.98             \n",
       "15  0.92             \n",
       "16  1.00             \n",
       "17  1.00             \n",
       "18  0.87             \n",
       "19  0.75             "
      ]
     },
     "execution_count": 22,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#top20 clusters from 2020 01 01-05\n",
    "df3[['cluster_size', 'pattern', 'mean_similarity']]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
