{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 37,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "from clusterlogs import pipeline"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "metadata": {},
   "outputs": [],
   "source": [
    "pd.set_option('display.max_colwidth', -1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "metadata": {},
   "outputs": [],
   "source": [
    "df = pd.read_csv('error0101.txt')\n",
    "#df = pd.read_csv('error0102.txt')\n",
    "#df = pd.read_csv('error0115.txt')\n",
    "#df = pd.read_csv('error0201.txt')\n",
    "#df = pd.read_csv('error0225.txt')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>error_message</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <td>0</td>\n",
       "      <td>globus_ftp_client: the server responded with an error 500 500-Command failed : System error in stat: No such file or directory  500-A system call failed: No such file or directory  500 End.</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>1</td>\n",
       "      <td>Error on XrdCl::CopyProcess::Run(): [ERROR] Server responded with an error: [3010] Write permission denied</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>2</td>\n",
       "      <td>globus_ftp_client: the server responded with an error 500 500-Command failed : System error in stat: No such file or directory  500-A system call failed: No such file or directory  500 End.</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>3</td>\n",
       "      <td>globus_ftp_client: the server responded with an error 500 Command failed : stat64 error: No such file or directory</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>4</td>\n",
       "      <td>globus_ftp_client: the server responded with an error 500 500-Command failed : System error in stat: No such file or directory  500-A system call failed: No such file or directory  500 End.</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                                                                                                                                                                      error_message\n",
       "0  globus_ftp_client: the server responded with an error 500 500-Command failed : System error in stat: No such file or directory  500-A system call failed: No such file or directory  500 End.   \n",
       "1  Error on XrdCl::CopyProcess::Run(): [ERROR] Server responded with an error: [3010] Write permission denied                                                                                      \n",
       "2  globus_ftp_client: the server responded with an error 500 500-Command failed : System error in stat: No such file or directory  500-A system call failed: No such file or directory  500 End.   \n",
       "3  globus_ftp_client: the server responded with an error 500 Command failed : stat64 error: No such file or directory                                                                              \n",
       "4  globus_ftp_client: the server responded with an error 500 500-Command failed : System error in stat: No such file or directory  500-A system call failed: No such file or directory  500 End.   "
      ]
     },
     "execution_count": 40,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(703546, 1)"
      ]
     },
     "execution_count": 41,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "metadata": {},
   "outputs": [],
   "source": [
    "cluster = pipeline.Chain(df, target='error_message', mode='create')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Tokenization finished\n",
      "Found 21755 equal groups\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/ntuckus/anaconda3/envs/test/lib/python3.6/site-packages/smart_open/smart_open_lib.py:402: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function\n",
      "  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Vectorization of tokens finished\n",
      "Vectorization of sentences is finished\n",
      "Vocabulary size = 18847\n",
      "Number of dimensions is 137\n",
      "DBSCAN finished with 393 clusters\n",
      "Matching Clusterization!\n",
      "Postprocessed with 282 clusters\n"
     ]
    }
   ],
   "source": [
    "cluster.process()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>pattern</th>\n",
       "      <th>indices</th>\n",
       "      <th>cluster_size</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <td>0</td>\n",
       "      <td>err: Communication error on send, err: [SE][][] httpg:/:/srm/: CGSI-gSOAP running on reports:</td>\n",
       "      <td>[662665, 561309, 580151, 524045, 671485, 355154, 227099, 340623, 403862, 541966, 13530, 13650, 13721, 28837, 82011, 116632, 117707, 117710, 117957, 131531, 131532, 131548, 131570, 131585, 131601, 142510, 142543, 150508, 152794, 152799, 153010, 164599, 164601, 164653, 164665, 164672, 170366, 174650, 174670, 176826, 176957, 201634, 201650, 201652, 201688, 201689, 201691, 201693, 202223, 202226, 202279, 202286, 202290, 202302, 202843, 202885, 294269, 294295, 296543, 296551, 296592, 296615, 296662, 297496, 298614, 298617, 298618, 298937, 299448, 299586, 378552, 403823, 404018, 404020, 406347, 406379, 422191, 422197, 422225, 422323, 422350, 431666, 431899, 444109, 447461, 447742, 447744, 517957, 517974, 517978, 518016, 518027, 518528, 518529, 518548, 518587, 519127, 519169, 541421, 541434, ...]</td>\n",
       "      <td>100544</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>1</td>\n",
       "      <td>Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: []</td>\n",
       "      <td>[1, 18, 83, 93, 110, 133, 184, 274, 287, 289, 297, 304, 359, 360, 394, 397, 400, 406, 429, 434, 439, 442, 450, 457, 461, 463, 465, 466, 481, 490, 495, 511, 525, 527, 533, 535, 549, 573, 577, 579, 591, 592, 622, 641, 670, 674, 694, 715, 722, 726, 763, 770, 809, 841, 844, 875, 879, 887, 888, 901, 909, 911, 937, 939, 960, 965, 970, 980, 1004, 1010, 1020, 1048, 1054, 1095, 1098, 1122, 1138, 1144, 1145, 1167, 1170, 1175, 1185, 1217, 1240, 1257, 1272, 1273, 1297, 1300, 1316, 1331, 1337, 1346, 1351, 1355, 1361, 1373, 1380, 1411, ...]</td>\n",
       "      <td>60088</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>7</td>\n",
       "      <td>Protocol not supported or path/url invalid: root:/:1094//atlasscratchdisk/rucio/tests///</td>\n",
       "      <td>[41310, 41369, 41437, 41522, 101955, 103616, 104196, 104261, 104503, 186502, 197847, 266042, 331741, 331947, 332055, 344237, 357650, 357691, 361859, 366514, 366630, 471010, 471216, 471482, 473303, 473432, 473909, 485400, 517221, 571724, 571725, 592146, 615007, 615395, 615520, 615734, 643412, 643479, 669270, 31410, 40735, 40980, 41311, 97108, 101752, 103097, 103145, 128048, 162314, 167669, 168062, 181775, 184079, 185623, 268117, 286862, 291776, 322521, 322702, 357169, 357326, 389365, 428490, 428821, 470485, 484978, 547813, 548070, 571691, 573767, 589364, 589435, 667350, 667375, 668771, 56837, 65602, 91981, 92138, 92278, 92531, 211305, 211397, 269804, 270706, 270801, 270848, 370773, 418732, 451406, 551348, 551587, 576451, 674997, 675240, 679371, 679468, 681219, 684654, 684658, ...]</td>\n",
       "      <td>45044</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>2</td>\n",
       "      <td>Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [4003] Authentication to:1094 failed; all protocols have been tried.</td>\n",
       "      <td>[277, 769, 969, 1947, 2287, 2330, 2352, 4173, 4619, 4847, 5950, 6320, 7429, 7795, 7887, 8942, 9047, 9722, 9723, 9853, 10126, 10241, 11778, 11877, 12379, 13349, 13819, 13979, 14089, 14713, 14924, 14980, 15698, 15970, 17107, 17843, 19349, 20843, 21317, 21675, 22112, 23194, 23807, 25268, 25312, 26215, 26399, 26446, 28278, 29348, 29682, 29725, 29785, 29818, 30003, 31567, 31775, 32991, 34953, 35372, 35490, 37490, 39886, 40679, 40781, 41326, 41475, 41619, 41988, 42412, 42530, 42544, 43188, 45374, 45457, 45565, 45911, 46504, 47869, 48304, 48445, 48451, 48584, 48896, 49143, 49539, 50290, 50810, 52137, 52497, 52800, 53657, 56561, 56587, 56685, 57398, 57536, 59408, 59450, 59946, ...]</td>\n",
       "      <td>29732</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>3</td>\n",
       "      <td>: the server responded with an error 500 500-Command failed : System error in: No such file or directory 500-A system call failed: No such file or directory 500 End.</td>\n",
       "      <td>[31917, 31921, 31979, 32562, 41353, 166551, 168232, 170116, 170201, 186321, 471127, 471227, 471771, 473453, 476462, 486004, 557910, 609548, 634215, 659854, 560, 629, 871, 872, 1651, 1901, 2142, 2293, 2298, 2458, 2549, 2799, 2974, 2980, 3079, 3082, 3167, 3512, 3513, 3712, 3747, 3748, 3790, 3793, 3925, 4012, 4136, 4188, 5056, 5061, 5131, 5245, 5252, 5511, 5683, 5684, 5851, 5921, 6027, 6098, 6349, 6541, 6616, 6617, 6719, 6798, 6971, 6995, 7109, 7232, 7245, 7307, 7576, 7664, 7668, 8073, 8169, 8225, 8226, 8356, 8444, 8458, 8609, 8650, 8700, 8763, 8846, 9020, 9022, 9072, 9139, 9145, 9202, 9335, 9339, 9358, 9414, 9710, 9776, 9865, ...]</td>\n",
       "      <td>29278</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>256</td>\n",
       "      <td>DESTINATION MAKE_PARENT srm:/｟*｠:8444/srm/managerv2?SFN=/cms/store/mc/PhaseIISummer17wmLHEGENOnly/DYJetsToLL_M-50_HT-200to400_TuneCUETP8M1_14TeV-madgraphMLM-pythia8/GEN/93X_upgrade2023_realistic_v5-v1/30000 it is a file</td>\n",
       "      <td>[409055]</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>257</td>\n",
       "      <td>TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: rejected PUT: 500 No such file or directory: 0000BD04ED40FD474537930F34EBB55B43F7; redirections [http:/158.37.63.149:27804/pnfs/ndgf.org/data/dteam/tpc/domatest/file9_832a22cb-e61d-4776-b1ba-573721fb4ca8?dcache-http-uuid=fe4bd3df-3d8f-49c1-8f72-8a830016dc0a]</td>\n",
       "      <td>[172962]</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>258</td>\n",
       "      <td>TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: verification failed: failed to connect to server:｟*｠: Read timed out</td>\n",
       "      <td>[215148]</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>259</td>\n",
       "      <td>TRANSFER globus_ftp_client: the server responded with an error 530 530-Login incorrect. : globus_gss_assist: Gridmap｟*｠ failure: Could not map /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=cmsrucio/CN=430796/CN=Robot: CMS Rucio Data Transfer 530- 530 End.</td>\n",
       "      <td>[305061]</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>281</td>\n",
       "      <td>DESTINATION SRM_PUTDONE Error on the surl srm:/lcg-lrz-srm.grid.lrz.de/pnfs/｟*｠/data/atlas/dq2/atlasdatadisk/rucio/tests/9b/46/ESD.4f5dd4be865c4842ac60661f5dea1c58 while putdone : [SE][PutDone][SRM_INVALID_PATH] No such file or directory: /pnfs/｟*｠/data/atlas/dq2/atlasdatadisk/rucio/tests/9b/46</td>\n",
       "      <td>[126165]</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>282 rows × 3 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                                                                                                                                                                                                                                                                                                                                      pattern  \\\n",
       "0    err: Communication error on send, err: [SE][][] httpg:/:/srm/: CGSI-gSOAP running on reports:                                                                                                                                                                                                                                                              \n",
       "1    Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: []                                                                                                                                                                                                                                                                               \n",
       "7    Protocol not supported or path/url invalid: root:/:1094//atlasscratchdisk/rucio/tests///                                                                                                                                                                                                                                                                   \n",
       "2    Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [4003] Authentication to:1094 failed; all protocols have been tried.                                                                                                                                                                                                             \n",
       "3    : the server responded with an error 500 500-Command failed : System error in: No such file or directory 500-A system call failed: No such file or directory 500 End.                                                                                                                                                                                      \n",
       "..                                                                                                                                                                     ...                                                                                                                                                                                      \n",
       "256  DESTINATION MAKE_PARENT srm:/｟*｠:8444/srm/managerv2?SFN=/cms/store/mc/PhaseIISummer17wmLHEGENOnly/DYJetsToLL_M-50_HT-200to400_TuneCUETP8M1_14TeV-madgraphMLM-pythia8/GEN/93X_upgrade2023_realistic_v5-v1/30000 it is a file                                                                                                                                \n",
       "257  TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: rejected PUT: 500 No such file or directory: 0000BD04ED40FD474537930F34EBB55B43F7; redirections [http:/158.37.63.149:27804/pnfs/ndgf.org/data/dteam/tpc/domatest/file9_832a22cb-e61d-4776-b1ba-573721fb4ca8?dcache-http-uuid=fe4bd3df-3d8f-49c1-8f72-8a830016dc0a]   \n",
       "258  TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: verification failed: failed to connect to server:｟*｠: Read timed out                                                                                                                                                                                                 \n",
       "259  TRANSFER globus_ftp_client: the server responded with an error 530 530-Login incorrect. : globus_gss_assist: Gridmap｟*｠ failure: Could not map /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=cmsrucio/CN=430796/CN=Robot: CMS Rucio Data Transfer 530- 530 End.                                                                                              \n",
       "281  DESTINATION SRM_PUTDONE Error on the surl srm:/lcg-lrz-srm.grid.lrz.de/pnfs/｟*｠/data/atlas/dq2/atlasdatadisk/rucio/tests/9b/46/ESD.4f5dd4be865c4842ac60661f5dea1c58 while putdone : [SE][PutDone][SRM_INVALID_PATH] No such file or directory: /pnfs/｟*｠/data/atlas/dq2/atlasdatadisk/rucio/tests/9b/46                                                    \n",
       "\n",
       "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              indices  \\\n",
       "0    [662665, 561309, 580151, 524045, 671485, 355154, 227099, 340623, 403862, 541966, 13530, 13650, 13721, 28837, 82011, 116632, 117707, 117710, 117957, 131531, 131532, 131548, 131570, 131585, 131601, 142510, 142543, 150508, 152794, 152799, 153010, 164599, 164601, 164653, 164665, 164672, 170366, 174650, 174670, 176826, 176957, 201634, 201650, 201652, 201688, 201689, 201691, 201693, 202223, 202226, 202279, 202286, 202290, 202302, 202843, 202885, 294269, 294295, 296543, 296551, 296592, 296615, 296662, 297496, 298614, 298617, 298618, 298937, 299448, 299586, 378552, 403823, 404018, 404020, 406347, 406379, 422191, 422197, 422225, 422323, 422350, 431666, 431899, 444109, 447461, 447742, 447744, 517957, 517974, 517978, 518016, 518027, 518528, 518529, 518548, 518587, 519127, 519169, 541421, 541434, ...]   \n",
       "1    [1, 18, 83, 93, 110, 133, 184, 274, 287, 289, 297, 304, 359, 360, 394, 397, 400, 406, 429, 434, 439, 442, 450, 457, 461, 463, 465, 466, 481, 490, 495, 511, 525, 527, 533, 535, 549, 573, 577, 579, 591, 592, 622, 641, 670, 674, 694, 715, 722, 726, 763, 770, 809, 841, 844, 875, 879, 887, 888, 901, 909, 911, 937, 939, 960, 965, 970, 980, 1004, 1010, 1020, 1048, 1054, 1095, 1098, 1122, 1138, 1144, 1145, 1167, 1170, 1175, 1185, 1217, 1240, 1257, 1272, 1273, 1297, 1300, 1316, 1331, 1337, 1346, 1351, 1355, 1361, 1373, 1380, 1411, ...]                                                                                                                                                                                                                                                                               \n",
       "7    [41310, 41369, 41437, 41522, 101955, 103616, 104196, 104261, 104503, 186502, 197847, 266042, 331741, 331947, 332055, 344237, 357650, 357691, 361859, 366514, 366630, 471010, 471216, 471482, 473303, 473432, 473909, 485400, 517221, 571724, 571725, 592146, 615007, 615395, 615520, 615734, 643412, 643479, 669270, 31410, 40735, 40980, 41311, 97108, 101752, 103097, 103145, 128048, 162314, 167669, 168062, 181775, 184079, 185623, 268117, 286862, 291776, 322521, 322702, 357169, 357326, 389365, 428490, 428821, 470485, 484978, 547813, 548070, 571691, 573767, 589364, 589435, 667350, 667375, 668771, 56837, 65602, 91981, 92138, 92278, 92531, 211305, 211397, 269804, 270706, 270801, 270848, 370773, 418732, 451406, 551348, 551587, 576451, 674997, 675240, 679371, 679468, 681219, 684654, 684658, ...]             \n",
       "2    [277, 769, 969, 1947, 2287, 2330, 2352, 4173, 4619, 4847, 5950, 6320, 7429, 7795, 7887, 8942, 9047, 9722, 9723, 9853, 10126, 10241, 11778, 11877, 12379, 13349, 13819, 13979, 14089, 14713, 14924, 14980, 15698, 15970, 17107, 17843, 19349, 20843, 21317, 21675, 22112, 23194, 23807, 25268, 25312, 26215, 26399, 26446, 28278, 29348, 29682, 29725, 29785, 29818, 30003, 31567, 31775, 32991, 34953, 35372, 35490, 37490, 39886, 40679, 40781, 41326, 41475, 41619, 41988, 42412, 42530, 42544, 43188, 45374, 45457, 45565, 45911, 46504, 47869, 48304, 48445, 48451, 48584, 48896, 49143, 49539, 50290, 50810, 52137, 52497, 52800, 53657, 56561, 56587, 56685, 57398, 57536, 59408, 59450, 59946, ...]                                                                                                                         \n",
       "3    [31917, 31921, 31979, 32562, 41353, 166551, 168232, 170116, 170201, 186321, 471127, 471227, 471771, 473453, 476462, 486004, 557910, 609548, 634215, 659854, 560, 629, 871, 872, 1651, 1901, 2142, 2293, 2298, 2458, 2549, 2799, 2974, 2980, 3079, 3082, 3167, 3512, 3513, 3712, 3747, 3748, 3790, 3793, 3925, 4012, 4136, 4188, 5056, 5061, 5131, 5245, 5252, 5511, 5683, 5684, 5851, 5921, 6027, 6098, 6349, 6541, 6616, 6617, 6719, 6798, 6971, 6995, 7109, 7232, 7245, 7307, 7576, 7664, 7668, 8073, 8169, 8225, 8226, 8356, 8444, 8458, 8609, 8650, 8700, 8763, 8846, 9020, 9022, 9072, 9139, 9145, 9202, 9335, 9339, 9358, 9414, 9710, 9776, 9865, ...]                                                                                                                                                                       \n",
       "..                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ...                                                                                                                                                                       \n",
       "256  [409055]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           \n",
       "257  [172962]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           \n",
       "258  [215148]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           \n",
       "259  [305061]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           \n",
       "281  [126165]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           \n",
       "\n",
       "     cluster_size  \n",
       "0    100544        \n",
       "1    60088         \n",
       "7    45044         \n",
       "2    29732         \n",
       "3    29278         \n",
       "..     ...         \n",
       "256  1             \n",
       "257  1             \n",
       "258  1             \n",
       "259  1             \n",
       "281  1             \n",
       "\n",
       "[282 rows x 3 columns]"
      ]
     },
     "execution_count": 44,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "cluster.result"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['Error on XrdCl::CopyProcess::Run(): [ERROR] Server responded with an error: [4003] Authentication to agh3.atlas.unimelb.edu.au:1094 failed; all protocols have been tried. '\n",
      " 'Error on XrdCl::CopyProcess::Run(): [ERROR] Server responded with an error: [4003] Authentication to agh3.atlas.unimelb.edu.au:1094 failed; all protocols have been tried. '\n",
      " 'Error on XrdCl::CopyProcess::Run(): [ERROR] Server responded with an error: [4003] Authentication to agh3.atlas.unimelb.edu.au:1094 failed; all protocols have been tried. '\n",
      " ...\n",
      " 'Error on XrdCl::CopyProcess::Run(): [ERROR] Server responded with an error: [4003] Authentication to xrootd.aglt2.org:1094 failed; all protocols have been tried. '\n",
      " 'Error on XrdCl::CopyProcess::Run(): [ERROR] Server responded with an error: [4003] Authentication to xrootd.aglt2.org:1094 failed; all protocols have been tried. '\n",
      " 'Error on XrdCl::CopyProcess::Run(): [ERROR] Server responded with an error: [4003] Authentication to xrootd.aglt2.org:1094 failed; all protocols have been tried. '] \n",
      "\n",
      "['DESTINATION OVERWRITE   HTTP 403 : Permission refused '\n",
      " 'DESTINATION OVERWRITE   HTTP 403 : Permission refused '\n",
      " 'DESTINATION OVERWRITE   HTTP 403 : Permission refused ' ...\n",
      " 'DESTINATION OVERWRITE   HTTP 403 : Permission refused '\n",
      " 'DESTINATION OVERWRITE   HTTP 403 : Permission refused '\n",
      " 'DESTINATION OVERWRITE   HTTP 403 : Permission refused ']\n"
     ]
    }
   ],
   "source": [
    "print(cluster.in_cluster(cluster.result, 2),\"\\n\") #some messages from the cluster 2\n",
    "print(cluster.in_cluster(cluster.result, 38)) #messages from the cluster without a clear pattern"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array(['err: Communication error on send, err: [SE][][] httpg:/:/srm/: CGSI-gSOAP running on reports:',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: []',\n",
       "       'Protocol not supported or path/url invalid: root:/:1094//atlasscratchdisk/rucio/tests///',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [4003] Authentication to:1094 failed; all protocols have been tried.',\n",
       "       ': the server responded with an error 500 500-Command failed : System error in: No such file or directory 500-A system call failed: No such file or directory 500 End.',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [] Unable to ////;',\n",
       "       'Destination file exists and overwrite is not enabled',\n",
       "       '｟*｠: Unable to connect to:2811｟*｠: System error in connect: Connection timed out｟*｠: A system call failed: Connection timed out',\n",
       "       'Error reported from srm_ifce : 2 [SE][Ls][SRM_INVALID_PATH] No such file or directory',\n",
       "       'end-of-file was reached｟*｠: An end of file occurred',\n",
       "       '[gfalt_copy_file][perform_copy][gfal_xrootd_3rd_copy][gfal_xrootd_3rd_copy_bulk] Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: []',\n",
       "       'SOURCE SRM_GET_TURL error on the turl request : [SE][][SRM_FILE_UNAVAILABLE] File is.',\n",
       "       'TRANSFER Transfer canceled because the gsiftp performance marker timeout of 360 seconds has been exceeded, or all performance markers during that period indicated zero bytes transferred',\n",
       "       'on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Unable to open /dpm/nipne.ro/home/atlas/atlasscratchdisk/rucio/tests///; no delegated credentials for tpc',\n",
       "       ': the server responded with an error 421 Service busy: Connection limit exceeded. Please try again later. Closing control connection.',\n",
       "       ': the server responded with an error 530 530-globus_xio: Authentication Error 530-OpenSSL Error: s3_srvr.c:: in library: SSL routines, function: certificate 530-globus_gsi_callback_module: Could not verify credential 530-globus_gsi_callback_module: The certificate: with subject: /=/=/OU=/CN=/CN=/CN=/CN=/CN=',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Access denied: /pnfs/triumf.ca/data/atlas/atlasscratchdisk/rucio/tests///',\n",
       "       'DESTINATION｟*｠ Connection timed out',\n",
       "       'on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3012] sync - TPC open failed for src_url=root:/://atlasscratchdisk/rucio/tests///?fst.readahead=true',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 Command failed. : open/create : [ERROR] Server responded with an error: [3021] Unable to get quota space - quota not defined or exhausted /eos/cms/store/user/bmarzocc//94X_mc2017-RunIIFall18/////; Disk quota',\n",
       "       'DESTINATION｟*｠ Result Authentication error, reached maximum number of｟*｠ after 1｟*｠',\n",
       "       'globus_ftp_control: gss_init_sec_context failed globus_gsi_gssapi: Error with gss credential handle globus_credential: Valid credentials could not be found in any of the possible locations specified by the credential search order. Valid credentials could not be found in any of the possible locations specified by the credential search order. Attempt 1 globus_credential: Error reading host credential globus_sysconfig: Error with certificate filename globus_sysconfig: Error with certificate filename globus_sy',\n",
       "       'srm-ifce err: Permission denied, err: [SE][Ls][SRM_AUTHORIZATION_FAILURE] httpg:/:8443/srm/managerv2:',\n",
       "       'error on the turl request : [SE][][] <none>',\n",
       "       ':: to verify remote sides credentials: handshake problems: Couldnt do ssl handshake',\n",
       "       'TRANSFER｟*｠ timed out',\n",
       "       'SOURCE CHECKSUM MISMATCH User defined checksum and source checksum do not match !=',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: problem sending data: Certificate for <> doesnt match any of the subject alternative names: [@]',\n",
       "       'SOURCE CHECKSUM globus_ftp_client: the server responded with an error 500 error:｟*｠ denied',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: copy HTTP 409 : Conflict, File Exist',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: copy Could not the proxy: fault: SOAP-ENV:Client [no subcode]: Detail:',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: Failed while waiting for mover to start: Failed to enqueue mover: CacheException(rc=27;msg=Could not create mover for RemoteHttpsDataTransfer-1.1:https:/://rucio////)',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: copy Could not get the delegation id: Could not get proxy request: SOAP 1.1 fault: SOAP-ENV:Client [no subcode] Detail: connect failed in tcp_connect()',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR]｟*｠ not supported: does not support third-party-copy',\n",
       "       'srm-ifce err: Communication error on send, err: [SE][Ls][] httpg:/srmcms.pic.es:8443/srm/managerv2: CGSI-gSOAP running on t3serv019.mit.edu reports Could NOT load client credentials GSS Major Status: General failure GSS Minor Status Error Chain: globus_gsi_gssapi: Error with GSI credential globus_gsi_gssapi: Error with gss credential handle globus_credential: Valid credentials could not be found in any of the possible locations specified by the credential search order. Valid credentials could not be foun',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [｟*｠] []',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][SRM_FAILURE] error accessing://cms/: Connection closed by remote end',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error:::::.',\n",
       "       ': the server responded with an error｟*｠: v=1 c=:: System error in:｟*｠ End.',\n",
       "       'DESTINATION｟*｠ HTTP｟*｠ : Permission｟*｠',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure:',\n",
       "       ': the server responded with an error｟*｠ 550-GlobusError: v=1 c=PATH_NOT_FOUND 550-GridFTP-Errno: 2 550-GridFTP-Reason: System error in 550-GridFTP-Error-String: No such file or directory｟*｠ End.',\n",
       "       'globus_ftp_client: the server responded with an error 500 failed.: to connect to:: error in connect: Connection 500-globus_xio: A system call failed: Connection 500 End.',\n",
       "       'TRANSFER｟*｠: System error in recv: Connection timed out｟*｠: A system call failed: Connection timed out',\n",
       "       '｟*｠: System error in: Connection reset by peer｟*｠: A system call failed: Connection reset by peer',\n",
       "       '[gfalt_copy_file][perform_copy][gfal_xrootd_3rd_copy][gfal_xrootd_3rd_copy_bulk] Error on XrdCl:CopyProcess:Run(): []',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3003] Output file /dpm/brunel.ac.uk/home/dteam/wlcg-tpc/root// is already opened by 1 writer; open denied.',\n",
       "       'DESTINATION SRM_PUTDONE call to srm_ifce error: [SE][PutDone][] httpg:/:/srm/managerv2: CGSI-gSOAP running on reports:',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3003] Output file /dteam:test1/domatest/ is already opened by 1 writer; open denied.',\n",
       "       ': the server responded with an error 530 530-Login incorrect. : globus_gss_assist: Error invoking｟*｠ 530-globus_callout_module: The｟*｠ returned an error 530-an unknown error occurred 530 End.',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. :｟*｠: The GSI XIO driver failed to establish a secure connection. The failure occured during a handshake read. 500-globus_xio: System error in recv: Connection reset by peer 500-globus_xio: A system call failed: Connection reset by peer 500 End.',\n",
       "       'No such file or directory',\n",
       "       '[gfalt_copy_file][perform_copy][gfal_http_copy] DESTINATION｟*｠ [gfal_http_copy_overwrite] [gfal_http_exists][gfal_http_access][davix2gliberr] Result Authentication error, reached maximum number of｟*｠ after 1｟*｠',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: Failed to select｟*｠: No｟*｠ candidates available/configured/left for stage',\n",
       "       'Error on XrdCl:CopyProcess:Run(): []',\n",
       "       ': the server responded with an error 530 Login incorrect. : Server over the user connection limit of (host=, user=)',\n",
       "       'TRANSFER ERROR: Copy failed with mode, with error: HTTP｟*｠ : Server Error',\n",
       "       'TRANSFER CHECKSUM MISMATCH and｟*｠', 'CHECKSUM｟*｠ timed out',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [FATAL]｟*｠ limit has been reached',\n",
       "       'and｟*｠ do not match',\n",
       "       'Error reported from srm_ifce : 2 [SE][Ls][SRM_INVALID_PATH] No such file or directory /pnfs///////',\n",
       "       ': the server responded with an error 500 Command failed :｟*｠ error: No',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error:',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 555 SRM upload aborted: Changing file｟*｠ because request｟*｠ has changed.',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: problem sending data:',\n",
       "       '[gfalt_copy_file][perform_copy][gfal_xrootd_3rd_copy][gfal_xrootd_3rd_copy_bulk] Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [4003] Authentication to ftp1.ndgf.org:1094 failed; all protocols have been tried.',\n",
       "       'Checksum value required if mode is not end to end',\n",
       "       'Source and destination file｟*｠',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error｟*｠',\n",
       "       'Result HTTP 404 : File not found after 1｟*｠',\n",
       "       'TRANSFER CHECKSUM MISMATCH and destination｟*｠ do not match !=｟*｠',\n",
       "       '｟*｠ timed out',\n",
       "       '[gfalt_copy_file][perform_copy][gfal_xrootd_3rd_copy][gfal_xrootd_3rd_copy_bulk] Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Unable to create /atlas/atlasscratchdisk/rucio/tests///; permission denied',\n",
       "       '[gfalt_copy_file][perform_copy][gfal_http_copy] DESTINATION｟*｠ [gfal_http_copy_overwrite] [gfal_http_exists][gfal_http_access][davix2gliberr] HTTP｟*｠ : Permission｟*｠',\n",
       "       '[gfalt_copy_file][perform_copy] TRANSFER [gfal_http_copy] ERROR: Copy failed with mode 3rd push, with error: [davix2gliberr] Transfer failed: failure: Remote failed with status code',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: while pushing https:/:/atlasscratchdisk/rucio/tests///:',\n",
       "       'TRANSFER ERROR: Copy failed with mode, with error:',\n",
       "       'srm-ifce err: Connection timed out, err: [SE][][ETIMEDOUT] httpg:/:/srm/managerv2: User timeout over',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Error string contains not valid UTF-8 chars',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error｟*｠｟*｠',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error｟*｠ General problem:',\n",
       "       'HTTP 500 :｟*｠ server error: 500 after 1｟*｠',\n",
       "       'DESTINATION CHECKSUM HTTP 404 : File not found',\n",
       "       'globus_ftp_client: the server responded with an error 530 Login incorrect. : Mapped user is invalid.',\n",
       "       'DESTINATION Result HTTP 500 :｟*｠ server error: 500 after 1｟*｠',\n",
       "       'ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: Remote copy failed with status code 0:',\n",
       "       ': the server responded with an error 500 Command failed :｟*｠ server error',\n",
       "       'CHECKSUM [｟*｠]｟*｠ canceled by user',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: Error pushing https:/:443/dpm//home/dteam//https/domatest/:',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: problem sending data: Connect to｟*｠: [｟*｠/] failed: timed out',\n",
       "       'SRM｟*｠ canceled',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 Command failed. :｟*｠',\n",
       "       'DESTINATION SRM_PUTDONE Error on the surl srm://dpm//home/atlas//rucio////. while putdone : [SE][PutDone][]',\n",
       "       ': the server responded with an error 421｟*｠: closing control connection.',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error｟*｠ Space reservation 229317465 may not be used for this write request [net=2001:1458:301::0:0:100:=GFtp/2,store=vo-atlas.ifae@enstore,cache=,linkgroup=linkgroup-atlast3]',\n",
       "       'DESTINATION SRM_PUTDONE Error on the surl srm:///data/////// while putdone : [SE][PutDone][SRM_INTERNAL_ERROR] PreparedStatementCallback; SQL [UPDATE t_inodes SET inlink=inlink +?,imtime=?,ictime=?,igeneration=igeneration+1 WHERE inumber=?]; ERROR: deadlock detected; Detail: Process waits for on',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. :｟*｠ error in: 500-globus_xio: A system call failed: 500 End.',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 555 SRM upload aborted: File was deleted by request::srm2:rm.',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error｟*｠ Post-processing failed: No such file or directory:｟*｠',\n",
       "       '[gfal2_stat][gfal_plugin_statG][davix2gliberr] Result HTTP 404 : File not found after 1｟*｠',\n",
       "       '｟*｠: Unable to connect to｟*｠:｟*｠: System error in connect: Connection｟*｠: A system call failed: Connection｟*｠',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Unable to open - tpc key replayed /eos//////;｟*｠ not permitted',\n",
       "       '[gfalt_copy_file][perform_copy] TRANSFER [gfal_http_copy] ERROR: Copy failed with mode 3rd, with error: [davix2gliberr]',\n",
       "       ': the server responded with an error 530 530-globus_xio: Authentication Error 530-globus_gsi_callback_module: Could not verify credential 530-globus_gsi_callback_module: Could not verify credential 530-globus_gsi_callback_module: Invalid｟*｠: The available｟*｠ has expired 530 End.',\n",
       "       'TRANSFER｟*｠ canceled from｟*｠', 'Transfer canceled',\n",
       "       'Error reported from srm_ifce : 16 [SE][Ls][SRM_FILE_BUSY] The requested SURL is locked by an upload.',\n",
       "       'DESTINATION SRM_PUTDONE Error on the surl srm:////cms/store///// while putdone : [SE][PutDone][]',\n",
       "       'TRANSFER globus_ftp_client: the｟*｠ was aborted',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error｟*｠ Protocol｟*｠ not supported',\n",
       "       'TRANSFER ERROR: Copy failed with mode｟*｠, with error: (Neon):',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error｟*｠ General problem: Failed to connect [2001:2f8:102d:589:2:3:1:]::',\n",
       "       '｟*｠', '｟*｠: System error in send:｟*｠: A system call failed:｟*｠',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: copy HTTP 500 :｟*｠ server error: 500',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][SRM_FILE_BUSY] The surl srm:////// is currently busy (ongoing put requests)',\n",
       "       'CHECKSUM globus_ftp_client: the｟*｠ was aborted',\n",
       "       'globus_ftp_client: the server responded with an error 500: v=1 c= 500-GridFTP-Errno: 500-GridFTP-Reason: System error in name 500-GridFTP-Error-String: 500- 500 End.',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error｟*｠ 426-GlobusError: v=1 c=DATA_CHANNEL_COMMUNICATION_FAILURE 426-GridFTP-Errno: 104 426-GridFTP-Reason: System error in name 426-GridFTP-Error-String: Connection reset by peer｟*｠ End.',\n",
       "       ': the server responded with an error 535 Authentication failed: The peers certificate with subjects DN CN====== was rejected. The peers certificate status is: FAILED The following validation errors were found: error at position in chain, problematic certificate subject: CN===',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error｟*｠ failed: File upload not｟*｠',\n",
       "       ': the server responded with an error 530 Login incorrect. : Server over the global connection limit of 250 (user has 0 transfers) (host=, user=cms, path=(null)',\n",
       "       'SOURCE SRM_GET_TURL error on the turl request : [SE][StatusOfGetRequest][SRM_FAILURE] Insufficient user privileges to trigger a tape recall or file replication to the t0cms service class',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error｟*｠ Post-processing failed: File｟*｠ (expected=1236084125, actual=1175977984)',\n",
       "       '｟*｠: Unable to connect to:2811｟*｠: globus_libc_getaddrinfo failed. globus_common: Name or service not known',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 Command failed. : Error closing｟*｠ file handle',\n",
       "       'CHECKSUM HTTP 500 :｟*｠ server error: 500',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 Command failed. :｟*｠ failed while｟*｠ to｟*｠ request',\n",
       "       'CHECKSUM globus_ftp_client: the server responded with an error 500｟*｠ server error 500- 500 End.',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. :: error in: Connection reset by peer 500-globus_xio: A system call failed: Connection reset by peer 500 End.',\n",
       "       '[｟*｠]｟*｠ canceled by user',\n",
       "       'Failure (Neon): Server certificate verification failed: certificate issued for a different hostname after 1｟*｠',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error｟*｠ General problem: Failed to connect:: Connection timed out',\n",
       "       ': the server responded with an error 500 error',\n",
       "       'globus_ftp_client: the server responded with an error 530 530-Login incorrect. : gridmap.c:globus_gss_assist_map_and_authorize:2017: 530-Error invoking｟*｠ 530-globus_callout.c:globus_callout_handle_call_type:920: 530-The｟*｠ returned an error 530-an unknown error occurred 530 End.',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [｟*｠] Unable to checksum /dpm//home/dteam/root//; invalid argument Got an error while querying the checksum!',\n",
       "       'DESTINATION CHECKSUM Connection｟*｠ during redirection on https:/:1094/cephfs/grid/atlas/atlaslocalgroupdisk/rucio////?authz=Bearer%',\n",
       "       'reported from srm_ifce : 70 [SE][Ls][SRM_INTERNAL_ERROR] Request to [>PnfsManager@local] timed out.',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error｟*｠ 451-GlobusError: v=1 c=INTERNAL_ERROR 451-GridFTP-Errno: 255 451-GridFTP-Reason: System error in HDFS (host=, user=, path=/store///////) 451-GridFTP-Error-String: Unknown error 255｟*｠ End.',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. : an end-of-file was reached 500-globus_xio: An end of file occurred 500 End.',\n",
       "       'SOURCE SRM_GET_TURL error on the turl request : [SE][StatusOfGetRequest][SRM_FAILURE] Failed to pin file [rc=10011,msg=org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after.].',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Connection｟*｠; Status of TPC request unknown',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. : 500 End.',\n",
       "       'Failed to stat file (Permission denied)',\n",
       "       'DESTINATION CHECKSUM Authentication error, reached maximum number of｟*｠',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. 500- : globus_ftp_control_local_pasv failed. 500-globus_xio: globus_l_xio_tcp_bind failed. 500-globus_xio: System error in bind: Address already in use 500-globus_xio: A system call failed: Address already in use 500 End.',\n",
       "       'DESTINATION MAKE_PARENT srm-ifce err: Permission denied, err: [SE][Mkdir][SRM_AUTHORIZATION_FAILURE] httpg:/｟*｠:8443/srm/managerv2: srm:/｟*｠/castor/cern.ch/grid/atlas/tzero/user/mlassnig/pilot/user.mlassnig.pilot.test.single.hits: No such file or directory',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][PrepareToPut][SRM_EXCEED_ALLOCATION] Space associated with the space token 30043703 is not enough to hold SURL.',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [4003] Invalid request; user not｟*｠',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR]｟*｠: Got an error while querying the checksum!',\n",
       "       'Error reported from srm_ifce : 13 [SE][Ls][SRM_AUTHORIZATION_FAILURE] No｟*｠ found for user!',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][][]',\n",
       "       ': the server responded with an error 530 Login incorrect. : Server is cancelling｟*｠ due to over-load limit (host=, user=, path=(null)',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: rejected PUT: 500 Server Error',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure::; redirections [:/:///2020-01-01/?sfn=%2Fdpm%%2Fhome%%%%&token=%',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][SRM_INVALID_PATH] ///cms/store/////',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error｟*｠ General problem: Problem while connected to:｟*｠',\n",
       "       'TRANSFER ERROR: Copy failed with mode｟*｠, with error: TRANSFER STREAMED DISABLED Trying to fallback to a｟*｠ copy, but they are disabled',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: copy (Neon): SSL handshake failed: Connection timed out during SSL handshake',\n",
       "       ': the server responded with an error 500 500-Command failed : System error in: Permission denied 500-A system call failed: Permission denied 500 End.',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][｟*｠] Cannot srmPut file because it already exists!',\n",
       "       'DESTINATION MAKE_PARENT srm-ifce err: Communication error on send, err: [SE][Mkdir][SRM_INTERNAL_ERROR] httpg:/grid-srm.physik.rwth-aachen.de:8443/srm/managerv2: srm:/grid-srm.physik.rwth-aachen.de/pnfs/physik.rwth-aachen.de/cms/store/data/Run2016H/Charmonium/MINIAOD/18Apr2017-v1/10000:｟*｠ name space timeout',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. : System error in name: Success 500-A system call failed: Success 500- 500 End.',\n",
       "       'DESTINATION SRM_PUTDONE call to srm_ifce error: [SE][PutDone][ETIMEDOUT] httpg:/｟*｠:8444/srm/managerv2: User timeout over',\n",
       "       'DESTINATION SRM_PUTDONE Error on the surl srm:/｟*｠/atlas/atlasdatadisk/rucio/mc16_13TeV///. while putdone : [SE][PutDone][]',\n",
       "       'DESTINATION CHECKSUM checksum calculation for ADLER32 not supported for davs:/atlas-fed-fe1.triumf.ca:443/dynafed/atlas/atlasdatadisk/rucio/mc16_13TeV///HITS.10701323.',\n",
       "       'DESTINATION MAKE_PARENT srm-ifce err: Permission denied, err: [SE][Mkdir][SRM_AUTHORIZATION_FAILURE] httpg:/:8443/srm/managerv2: srm://castor/ads.rl.ac.uk/prod///////: User can not create a directory at this level',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. :: Unable to connect to 2A0E:E140:: 500-globus_xio: System error in connect: Network is unreachable 500-globus_xio: A system call failed: Network is unreachable 500 End.',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3007] connection timed out: lcg-se01.icepp.jp/2001:2f8:102d:589:2:1:2:1:1094',\n",
       "       'DESTINATION error on the turl request : [SE][][SRM_FAILURE] Unable to build the TURL for the provided｟*｠ protocol',\n",
       "       'Error reported from srm_ifce : 2 [SE][Ls][SRM_INVALID_PATH] File does not｟*｠',\n",
       "       ': the server responded with an error 500 500-GlobusError: v=1 c=INTERNAL_ERROR 500-GridFTP-Errno: 500-GridFTP-Reason: System error in name 500-GridFTP-Error-String: 500- 500 End.',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: copy (Neon): Could not read status｟*｠:',\n",
       "       'Connection timed out',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. : callback failed. 500-globus_xio: System error in write: Disk quota exceeded 500-globus_xio: A system call failed: Disk quota exceeded 500 End.',\n",
       "       'CHECKSUM timeout of｟*｠',\n",
       "       'DESTINATION｟*｠ error reported from srm_ifce, [SE][srmRm][SRM_INTERNAL_ERROR]｟*｠ out',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 Command failed. : open error: Permission denied',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 530 Login failed: Request to [>｟*｠@local] timed out.',\n",
       "       'reported from srm_ifce : 70 [SE][Ls][SRM_INTERNAL_ERROR] Failed to｟*｠ transfers',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 Command failed. : an unknown error occurred',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error｟*｠ General problem: Failed to connect [2001:6a0:2001:112:12]::',\n",
       "       'SOURCE SRM_GET_TURL error on the turl request : [SE][StatusOfGetRequest][SRM_INTERNAL_ERROR]｟*｠',\n",
       "       'Result Authentication error, reached maximum number of｟*｠ after 1｟*｠',\n",
       "       '[gfalt_copy_file][perform_copy] TRANSFER [gfal_http_copy] ERROR: Copy failed with mode 3rd push, with error: [davix2gliberr] Transfer failed: failure: verification failed: failed to connect to server:｟*｠: Read timed out',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [｟*｠] [ERROR] Server responded with an error: [] Unable to ///atlasscratchdisk/rucio/tests///;',\n",
       "       'globus_ftp_client: the server responded with an error 500｟*｠ error in: No such file or directory 500-A system call failed: No such file or directory 500 End.',\n",
       "       'DESTINATION CHECKSUM globus_ftp_client: the server responded with an error｟*｠ Error retrieving /pnfs/nikhef.nl/data/atlas/atlasdatadisk/rucio/mc15_13TeV///TXT.13045593.: No such file or directory /pnfs/nikhef.nl/data/atlas/atlasdatadisk/rucio/mc15_13TeV///TXT.13045593.',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 Command failed. : open : [ERROR] Server responded with an error: [｟*｠] Unable to open file /eos/cms/store/temp/user///////; No such file or directory',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][SRM_FAILURE] error chowning｟*｠://cms/2020-01-02:｟*｠ not permitted (error 1 on｟*｠)',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error｟*｠ General problem: Problem while connected to [2001:bf8:900:d:2:71]:: La m quina remota ha reiniciat la connexi',\n",
       "       'srm-ifce err: Communication error on send, err: [SE][Ls][] httpg:/｟*｠:8444/srm/managerv2: HTTP/｟*｠ Forbidden',\n",
       "       'Connection｟*｠',\n",
       "       'SOURCE SRM_GET_TURL error on the turl request : [SE][StatusOfGetRequest][SRM_FAILURE] Local filesystem mask does not allow setting up correct ACLs for PtG!',\n",
       "       'globus_ftp_client: the｟*｠ was aborted',\n",
       "       ': the server responded with an error 530 Login incorrect. : Invalid group id assigned to user｟*｠.',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][SRM_FILE_BUSY] The surl srm:/｟*｠/cms/store/user/raly/MonoHiggs/FullRunII/Data2017processing/DoubleEG/DoubleEG_Run2017F-31Mar2018-v1/191228_161827/0009/log/cmsRun_9390.log.tar.gz is currently busy (ongoing put requests)',\n",
       "       'DESTINATION SRM_PUTDONE Error on the surl srm:/｟*｠/pnfs/lcg.cscs.ch/cms/trivcat/store/PhEDEx_LoadTest07//// while putdone : [SE][PutDone][SRM_INVALID_PATH] No such file or directory: /pnfs/lcg.cscs.ch/cms/trivcat/store/PhEDEx_LoadTest07///',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: Failed sending data to the peer',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010]｟*｠ is no｟*｠ valid.',\n",
       "       'TRANSFER ERROR: Copy failed with mode｟*｠, with error: HTTP 500 :｟*｠ server error: 500 after 1｟*｠',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: copy HTTP｟*｠ :｟*｠ Not｟*｠, Permission｟*｠',\n",
       "       'DESTINATION SRM_PUTDONE Error on the surl srm:/｟*｠/cms/store/user/scalzafe/ME0GE11_muonGun///0000/ while putdone : [SE][PutDone][SRM_INVALID_PATH] PtP status for this SURL is SRM_ABORTED',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3012]｟*｠ failed Got an error while querying the checksum!',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: Error pushing https:/dynafed-atlas.cern.ch:443/data/dteam/s3/domatest/: 404 Not Found',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500｟*｠ error in｟*｠: Connection｟*｠ 500-A system call failed: Connection｟*｠ 500 End.',\n",
       "       '｟*｠: Unable to connect to gridftp.hepgrid.uerj.br:2811｟*｠: globus_libc_getaddrinfo failed. globus_common:',\n",
       "       '[gfalt_copy_file][perform_copy][gfal_xrootd_3rd_copy][gfal_xrootd_3rd_copy_bulk] Error on XrdCl:CopyProcess:Run(): [ERROR]｟*｠: Got an error while querying the checksum!',\n",
       "       'globus_ftp_client: the server responded with an error 500｟*｠ server error',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 Command failed. : Failed to close file in HDFS. (host=, user=, path=/store///////)',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: copy 0) Renewal failedSOAP 1.1 fault: SOAP-ENV:Server.generalException [no subcode] delegation already started for /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=ddmadmin/CN=531497/CN=Robot: ATLAS Data Management with id 1234 Detail: <ns1:DelegationException xmlns:ns1=http:/www.gridsite.org/namespaces/delegation-2><msg>delegation already started for /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=ddmadmin/CN=531497/CN=Robot: ATLAS Data Management with id 1234</msg></ns1:DelegationException> .',\n",
       "       'Transfer process died with: /｟*｠/libfts_common.so.3(_ZN4fts36common5panic13get_backtraceEi+0x21) [] /｟*｠/libfts_common.so.3(+0x18f6f) [] /｟*｠/libpthread.so.0(+0xf5f0) [] /｟*｠/libpthread.so.0(raise+0x2b) [] /usr/｟*｠/gfal2-plugins/libgfal_plugin_mock.so(gfal_plugin_mock_stat+0x23b) [] /｟*｠/libgfal2.so.2(gfal_plugin_statG+0xbb) [] /｟*｠/libgfal2.so.2(gfal2_stat+0x5e) [] /｟*｠/libfts_url_copy.so(_ZN5Gfal24statER19Gfal2TransferParamsRKSsb+0xac) [] /｟*｠/libfts_url_copy.so(_ZN14UrlCopyProcess11runTransferER8TransferR19Gfal2TransferParams+0xc29) [] /｟*｠/libfts_url_copy.so(_ZN14UrlCopyProcess3runEv+0x5cb) [] fts_url_copy(main+0x103) [] /｟*｠/libc.so.6(__libc_start_main+0xf5) [] fts_url_copy(+0x6741) []',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. : an I/O｟*｠ was cancelled 500-globus_xio:｟*｠ was canceled 500 End.',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [｟*｠] [ERROR] Server responded with an error: []｟*｠',\n",
       "       'TRANSFER｟*｠: Unable to connect to｟*｠:2811｟*｠: System error in connect: No｟*｠ to host｟*｠: A system call failed: No｟*｠ to host',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl gsiftp:/:2811/gpfs/storage_3/atlas/atlasdatadisk/rucio/mc16_13TeV///HITS.19909364. request : [SE][StatusOfPutRequest][SRM_ABORTED] File has been removed.',\n",
       "       'DESTINATION CHECKSUM (Neon): SSL handshake failed: Connection timed out during SSL handshake',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: Failed: Remote copy failed with status code 0: cipher-suite not supported by NSS: rsa_rc4_40_md5',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3007] connection timed out:/｟*｠:1094',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 Command failed. : Error registering globus write error: Unknown error 2033',\n",
       "       'DESTINATION CHECKSUM error on the turl request : [SE][StatusOfGetRequest][SRM_INVALID_PATH] The requested file｟*｠ does not｟*｠, or it is a directory!',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 452 All pools are full',\n",
       "       'DESTINATION MAKE_PARENT srm-ifce err: No such file or directory, err: [SE][Mkdir][SRM_INVALID_PATH] httpg:/:8443/srm/managerv2: No such file or directory',\n",
       "       'globus_ftp_client: the server responded with an error｟*｠ No such file or directory',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. :｟*｠: Unable to connect to 2001:610:108:203A:0:0:1::22224 500-globus_xio: System error in connect: Permission denied 500-globus_xio: A system call failed: Permission denied 500 End.',\n",
       "       'DESTINATION SRM_PUTDONE Error on the surl srm:/se01.indiacms.res.in/dpm/indiacms.res.in/home/cms/store/user/////// while putdone : [SE][PutDone][SRM_INTERNAL_ERROR]｟*｠ out',\n",
       "       'SOURCE CHECKSUM globus_ftp_client: the server responded with an error｟*｠ Checksum is not available,｟*｠ checksum calculation is not supported',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error｟*｠ 550-GlobusError: v=1 c=PERMISSION_DENIED 550-GridFTP-Errno: 13 550-GridFTP-Reason: System error in mkdir (host=, user=cmsphedx, path=/store/generator/Summer13/GluGluToHHToTauTauBB_M-125_14TeV-powheg-pythia6/GEN/UpgrdPhase1Age5H_STAR17_61_V5A-v1/00000) 550-GridFTP-Error-String: Permission denied｟*｠ End.',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: Remote copy failed with status code 0: Failed to connect to｟*｠ 443:',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: failed to connect to server: javax.net.ssl.SSLPeerUnverifiedException: Certificate for <dynafed02.heprc.uvic.ca> doesnt match any of the subject alternative names: [mebert@uvic.ca]',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 Cannot enter passive mode: java.net.SocketException: Invalid argument',\n",
       "       '[gfalt_copy_file][perform_copy][srm_plugin_filecopy] SOURCE CHECKSUM [srm_validate_source_checksum][gfal_srm_checksumG_fallback][｟*｠][｟*｠] error on the turl request : [SE][StatusOfGetRequest][SRM_FAILURE] Failure in PolicySource prevented PolicyCollector from establishing access rights! Processing failed!',\n",
       "       'DESTINATION EXISTS Destination already｟*｠ gsiftp:/eoscmsftp.cern.ch/eos/cms/store/mc///GEN/106X_upgrade2018_realistic_v4-v1//, Cancel',\n",
       "       '[gfal2_stat][gfal_plugin_statG][｟*｠] Failed to stat file (Permission denied)',\n",
       "       'Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [｟*｠] Unable to open /dpm//home/dteam/root/test/｟*｠; file exists',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][SRM_INTERNAL_ERROR] error accessing stor110.cis.gov.pl:/mnt/dpm/cms/cms/2020-01-01:｟*｠ out',\n",
       "       '[][][][｟*｠][｟*｠] Error reported from srm_ifce : 13 [SE][Ls][SRM_AUTHORIZATION_FAILURE] User does not have valid permissions',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][SRM_INTERNAL_ERROR] Request to [>PnfsManager@local] timed out.',\n",
       "       'TRANSFER｟*｠: Unable to connect to｟*｠:2811｟*｠: globus_xio_system_socket_register_connect failed.｟*｠: System error in connect: Network is unreachable｟*｠: A system call failed: Network is unreachable',\n",
       "       'DESTINATION CHECKSUM MISMATCH Source and destination ADLER32 do not match (｟*｠ !=｟*｠)',\n",
       "       'SOURCE SRM_GET_TURL srm-ifce err: Connection reset by peer, err: [SE][｟*｠][] httpg:/srm-eoslhcb.cern.ch:8443/srm/v2/server: CGSI-gSOAP running on reports Error reading token data header: Connection reset by peer',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error｟*｠ Unable to｟*｠ space: no｟*｠ configured.',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: Failed to｟*｠ file: No｟*｠ to [>PnfsManager@local]',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][PrepareToPut][SRM_ABORTED] Request aborted.',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: Failed to select｟*｠: Request to [>｟*｠@｟*｠] timed out.',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl gsiftp:/ss-01.recas.ba.infn.it:2811/lustre/cms/store/user/raly/MonoHiggs/FullRunII/Data2017processing/DoubleMuon/DoubleMuon_Run2017C-31Mar2018-v1/191228_155526/0004/roottree_leptons_4769.root request : [SE][StatusOfPutRequest][SRM_ABORTED] File has been removed.',\n",
       "       'DESTINATION SRM_PUTDONE call to srm_ifce error: [SE][PutDone][SRM_FAILURE] httpg:/se03.esc.qmul.ac.uk:8444/srm/managerv2: Failed to｟*｠ request:｟*｠ was reached.',\n",
       "       'DESTINATION CHECKSUM globus_ftp_client: the server responded with an error 500 500-Command failed : globus_xio_register_open failed. 500-globus_xio: Unable to open file /lustre/cms/store/user/raly/MonoHiggs/FullRunII/Data2017processing/DoubleEG/DoubleEG_Run2017C-31Mar2018-v1/191228_161253/0002/roottree_leptons_2429.root 500-globus_xio: System error in open: No such file or directory 500-globus_xio: A system call failed: No such file or directory 500 End.',\n",
       "       'TRANSFER globus_ftp_control: gss_init_sec_context failed GSS Major Status:｟*｠ Gatekeeper or Service Name globus_gsi_gssapi: Authorization denied: The name of the remote entity (/DC=org/DC=terena/DC=tcs/C=ES/ST=Barcelona/L=Bellaterra/O=Port dInformacio Cientifica/CN=door04.pic.es), and the expected name for the remote entity (/CN=2001:67c:1148:｟*｠:0:0:0:14) do not match',\n",
       "       'SOURCE SRM_GET_TURL srm-ifce err:｟*｠ not supported, err: [SE][PrepareToGet][｟*｠] httpg:/｟*｠:8443/srm/managerv2: Protocol(s) not supported: [gsiftp]',\n",
       "       'SOURCE SRM_GET_TURL error on the turl request : [SE][StatusOfGetRequest][SRM_AUTHORIZATION_FAILURE] Read access to srm:/se03.esc.qmul.ac.uk/atlas/atlasdatadisk/rucio/mc16_13TeV/38/d9/HITS.19746424._004299.pool.root.1 denied!',\n",
       "       'SOURCE SRM_GET_TURL error on the turl request : [SE][StatusOfGetRequest][｟*｠] Failed to process any of the｟*｠',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 500 500-Command failed. : /builddir/build/BUILD/gridftp-hdfs-1.1.1/src/gridftp_hdfs_recv.c:close_and_clean:61: 500-Failed to close file in HDFS. (host=gftp-5.t2.ucsd.edu, user=cmswriter, path=/cms/phedex/store/data/Run2017B/ZeroBias/AOD/17Nov2017-v1/40000/7C6B99E9-EFCF-E711-9E82-4C79BA1814BF.root) 500 End.',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error｟*｠ General problem: Stream was closed in the｟*｠ of a｟*｠',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error｟*｠ General problem: Problem while connected to｟*｠:｟*｠: Connection timed out',\n",
       "       'DESTINATION SRM_PUTDONE Error on the surl srm:/｟*｠/cms/store/user/raly/MonoHiggs/FullRunII/Data2017processing/DoubleMuon/DoubleMuon_Run2017F-31Mar2018-v1/191228_160208/0008/log/cmsRun_8568.log.tar.gz while putdone : [SE][PutDone][SRM_INVALID_PATH] PtP status for this SURL is SRM_ABORTED',\n",
       "       'DESTINATION SRM_PUTDONE Error on the surl srm:/svr018.gla.scotgrid.ac.uk/dpm/gla.scotgrid.ac.uk/home/atlas/atlasdatadisk/rucio/user/gjakel/08/c2/user.gjakel.20032291._000122.out.root while putdone : [SE][PutDone][SRM_FILE_LIFETIME_EXPIRED] <none>',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error｟*｠ General problem: Failed to connect｟*｠:｟*｠: No｟*｠ to host',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error｟*｠ General problem: Failed to connect [2406:f00:9:2c]:｟*｠:',\n",
       "       'DESTINATION CHECKSUM globus_ftp_client: the server responded with an error｟*｠ Error retrieving /pnfs/nikhef.nl/data/atlas/atlasdatadisk/rucio/mc15_13TeV/3a/fa/TXT.13045593._006134.tar.gz.1: File upload not｟*｠',\n",
       "       'Result (Neon): SSL handshake failed: Connection timed out during SSL handshake after 1｟*｠',\n",
       "       'DESTINATION MAKE_PARENT srm-ifce err: Communication error on send, err: [SE][Mkdir][SRM_INTERNAL_ERROR] httpg:/dcsrm.usatlas.bnl.gov:8443/srm/managerv2: srm:/dcsrm.usatlas.bnl.gov/pnfs/usatlas.bnl.gov/BNLT0D1/rucio/user/mvozak/bd/32:｟*｠ name space timeout',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: copy 0) Could not PUT the proxy: Error -1 fault: SOAP-ENV:Client [no subcode] End of file or no input:｟*｠ interrupted or timed out Detail: [no detail] .',\n",
       "       '[gfalt_copy_file][perform_copy] TRANSFER [gfal_http_copy] ERROR: Copy failed with mode 3rd push, with error: [davix2gliberr] Transfer failed: failure: delete of remote file (triggered by failed to connect to server:｟*｠: Read timed out) failed: rejected DELETE:｟*｠ Forbidden',\n",
       "       'DESTINATION｟*｠ DavPosix:｟*｠ HTTP 500 :｟*｠ server error: 500 with url davs:/dcgftp.usatlas.bnl.gov:443/pnfs/usatlas.bnl.gov/atlasscratchdisk/rucio/tests/26/67/file26_533d06f5-59a4-4a10-a219-2e8e422d591f',\n",
       "       'Protocol not supported or path/url invalid:｟*｠:/｟*｠:8443/data',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][SRM_AUTHORIZATION_FAILURE] Create/Write access to srm:/se03.esc.qmul.ac.uk/atlas/atlasscratchdisk/rucio/user/jeliu/17/85/user.jeliu.20187989._000015.tree.root denied!',\n",
       "       'DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][SRM_FAILURE] error accessing belle2grid4.cc.ntu.edu.tw:/data11/belle/2020-01-02: Connection timed out',\n",
       "       'Failed to stat file (No such file or directory)',\n",
       "       'SOURCE CHECKSUM Connection｟*｠ during redirection on https:/cmsio8.rc.ufl.edu:1094/store/PhEDEx_LoadTest07/LoadTest07_Debug_US_Florida/US_Nebraska/460/LoadTest07_Florida_8E_reRRUy7I2clZ3J6e_460?authz=Bearer%20MDAxYmxvY2F0aW9uIFQyX1VTX0Zsb3JpZGEKMDAzNGlkZW50aWZpZXIgOWQ1MGQzNzAtNmNiYi00NTVkLWJkNGQtZDA2NTM5MWM5NGYwCjAwMTVjaWQgbmFtZTpjbXMwMDAxCjAwMmRjaWQgYWN0aXZpdHk6UkVBRF9NRVRBREFUQSxET1dOTE9BRCxMSVNUCjAwMWZjaWQgYWN0aXZpdHk6RE9XTkxPQUQsTElTVAowMDdkY2lkIHBhdGg6L3N0b3JlL1BoRURFeF9Mb2FkVGVzdDA3L0xvYWRUZXN0MDdfRGVidWdfVVNfR',\n",
       "       'DESTINATION CHECKSUM checksum calculation for ADLER32 not supported for davs:/head01.aglt2.org:2880/atlasscratchdisk/rucio/tests/93/e7/file21_41789f84-1f53-4b0b-8616-dcf11860886f',\n",
       "       '[gfalt_copy_file][perform_copy] DESTINATION CHECKSUM [gfal_http_copy][｟*｠][davix2gliberr] HTTP 500 :｟*｠ server error: 500',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: Failed while waiting for mover to start: Could not create mover for RemoteHttpsDataTransfer-1.1:https:/dynafed02.heprc.uvic.ca:8443/atlas/scratchdisk/rucio/mc16_13TeV/fe/21/AOD.11982116._000010.pool.root.1',\n",
       "       'DESTINATION SRM_PUTDONE Error on the surl srm:/dcsrm.usatlas.bnl.gov/pnfs/usatlas.bnl.gov/BNLT0D1/rucio/mc16_13TeV/22/75/DAOD_TOPQ1.20044786._002380.pool.root.1 while putdone : [SE][PutDone][SRM_INTERNAL_ERROR] Request to [>PnfsManager@local] timed out.',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: Remote copy failed with status code 0: Failed to connect to 2001:48a8:68f7:1:192:41:231:128｟*｠ 38260: Bad file descriptor',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: Too many｟*｠ to select｟*｠; last｟*｠ pool20_1@pool20Domain failed with Could not create MoverProtocol mover for RemoteHttpsDataTransfer-1.1:https:/dynafed02.heprc.uvic.ca:8443/atlas/scratchdisk/rucio/mc16_13TeV/fe/21/AOD.11982116._000010.pool.root.1: directory not found: /etc/grid-security/certificates',\n",
       "       'DESTINATION MAKE_PARENT srm:/｟*｠:8444/srm/managerv2?SFN=/cms/store/mc/PhaseIISummer17wmLHEGENOnly/DYJetsToLL_M-50_HT-200to400_TuneCUETP8M1_14TeV-madgraphMLM-pythia8/GEN/93X_upgrade2023_realistic_v5-v1/30000 it is a file',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: rejected PUT: 500 No such file or directory: 0000BD04ED40FD474537930F34EBB55B43F7; redirections [http:/158.37.63.149:27804/pnfs/ndgf.org/data/dteam/tpc/domatest/file9_832a22cb-e61d-4776-b1ba-573721fb4ca8?dcache-http-uuid=fe4bd3df-3d8f-49c1-8f72-8a830016dc0a]',\n",
       "       'TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: verification failed: failed to connect to server:｟*｠: Read timed out',\n",
       "       'TRANSFER globus_ftp_client: the server responded with an error 530 530-Login incorrect. : globus_gss_assist: Gridmap｟*｠ failure: Could not map /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=cmsrucio/CN=430796/CN=Robot: CMS Rucio Data Transfer 530- 530 End.',\n",
       "       'DESTINATION SRM_PUTDONE Error on the surl srm:/lcg-lrz-srm.grid.lrz.de/pnfs/｟*｠/data/atlas/dq2/atlasdatadisk/rucio/tests/9b/46/ESD.4f5dd4be865c4842ac60661f5dea1c58 while putdone : [SE][PutDone][SRM_INVALID_PATH] No such file or directory: /pnfs/｟*｠/data/atlas/dq2/atlasdatadisk/rucio/tests/9b/46'],\n",
       "      dtype=object)"
      ]
     },
     "execution_count": 46,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "cluster.result['pattern'].values"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 71,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>pattern</th>\n",
       "      <th>indices</th>\n",
       "      <th>cluster_size</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <td>151</td>\n",
       "      <td>DESTINATION SRM_PUT_TURL error on the turl request : [SE][][]</td>\n",
       "      <td>[372822, 62752, 127534, 245582, 326861, 326862, 356450, 423298, 517856, 602046, 628326, 97186, 97339, 127954, 162337, 322490, 322501, 389078, 389344, 428354, 428491, 547868, 589335, 678740, 685320, 692718, 697973, 372460]</td>\n",
       "      <td>28</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>153</td>\n",
       "      <td>: the server responded with an error 530 Login incorrect. : Server is cancelling｟*｠ due to over-load limit (host=, user=, path=(null)</td>\n",
       "      <td>[351287, 143296, 251613, 657498, 657516, 539240, 356062, 356073, 656942, 288424, 523188, 412903, 563786, 651595, 177875, 584269, 639959, 61588, 317714, 397335, 397353, 631311, 248440, 539263, 607077, 217650]</td>\n",
       "      <td>26</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>154</td>\n",
       "      <td>TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: rejected PUT: 500 Server Error</td>\n",
       "      <td>[64601, 84287, 103443, 104897, 104947, 122504, 140794, 172848, 174014, 193086, 236732, 244520, 251075, 311722, 319463, 368972, 373854, 398063, 443320, 562760, 564532, 572995, 598557, 612724]</td>\n",
       "      <td>24</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>155</td>\n",
       "      <td>TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure::; redirections [:/:///2020-01-01/?sfn=%2Fdpm%%2Fhome%%%%&amp;token=%</td>\n",
       "      <td>[252606, 297310, 303922, 139774, 32751, 545306, 216602, 278783, 149347, 527711, 631097, 527712, 590115, 601910, 198774, 276209, 40812, 229111, 179348, 401451, 48035, 529526, 191457, 454507]</td>\n",
       "      <td>24</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>156</td>\n",
       "      <td>DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][SRM_INVALID_PATH] ///cms/store/////</td>\n",
       "      <td>[157162, 110992, 297177, 578505, 386389, 168976, 558468, 358786, 314758, 225297, 237404, 180602, 48813, 119686, 119689, 636855, 196105, 197381, 467373, 89336, 568706, 568473]</td>\n",
       "      <td>22</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>256</td>\n",
       "      <td>DESTINATION MAKE_PARENT srm:/｟*｠:8444/srm/managerv2?SFN=/cms/store/mc/PhaseIISummer17wmLHEGENOnly/DYJetsToLL_M-50_HT-200to400_TuneCUETP8M1_14TeV-madgraphMLM-pythia8/GEN/93X_upgrade2023_realistic_v5-v1/30000 it is a file</td>\n",
       "      <td>[409055]</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>257</td>\n",
       "      <td>TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: rejected PUT: 500 No such file or directory: 0000BD04ED40FD474537930F34EBB55B43F7; redirections [http:/158.37.63.149:27804/pnfs/ndgf.org/data/dteam/tpc/domatest/file9_832a22cb-e61d-4776-b1ba-573721fb4ca8?dcache-http-uuid=fe4bd3df-3d8f-49c1-8f72-8a830016dc0a]</td>\n",
       "      <td>[172962]</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>258</td>\n",
       "      <td>TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: verification failed: failed to connect to server:｟*｠: Read timed out</td>\n",
       "      <td>[215148]</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>259</td>\n",
       "      <td>TRANSFER globus_ftp_client: the server responded with an error 530 530-Login incorrect. : globus_gss_assist: Gridmap｟*｠ failure: Could not map /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=cmsrucio/CN=430796/CN=Robot: CMS Rucio Data Transfer 530- 530 End.</td>\n",
       "      <td>[305061]</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>281</td>\n",
       "      <td>DESTINATION SRM_PUTDONE Error on the surl srm:/lcg-lrz-srm.grid.lrz.de/pnfs/｟*｠/data/atlas/dq2/atlasdatadisk/rucio/tests/9b/46/ESD.4f5dd4be865c4842ac60661f5dea1c58 while putdone : [SE][PutDone][SRM_INVALID_PATH] No such file or directory: /pnfs/｟*｠/data/atlas/dq2/atlasdatadisk/rucio/tests/9b/46</td>\n",
       "      <td>[126165]</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>130 rows × 3 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                                                                                                                                                                                                                                                                                                                                      pattern  \\\n",
       "151  DESTINATION SRM_PUT_TURL error on the turl request : [SE][][]                                                                                                                                                                                                                                                                                              \n",
       "153  : the server responded with an error 530 Login incorrect. : Server is cancelling｟*｠ due to over-load limit (host=, user=, path=(null)                                                                                                                                                                                                                      \n",
       "154  TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: rejected PUT: 500 Server Error                                                                                                                                                                                                                                       \n",
       "155  TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure::; redirections [:/:///2020-01-01/?sfn=%2Fdpm%%2Fhome%%%%&token=%                                                                                                                                                                                                     \n",
       "156  DESTINATION SRM_PUT_TURL error on the turl request : [SE][StatusOfPutRequest][SRM_INVALID_PATH] ///cms/store/////                                                                                                                                                                                                                                          \n",
       "..                                                                                                                 ...                                                                                                                                                                                                                                          \n",
       "256  DESTINATION MAKE_PARENT srm:/｟*｠:8444/srm/managerv2?SFN=/cms/store/mc/PhaseIISummer17wmLHEGENOnly/DYJetsToLL_M-50_HT-200to400_TuneCUETP8M1_14TeV-madgraphMLM-pythia8/GEN/93X_upgrade2023_realistic_v5-v1/30000 it is a file                                                                                                                                \n",
       "257  TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: rejected PUT: 500 No such file or directory: 0000BD04ED40FD474537930F34EBB55B43F7; redirections [http:/158.37.63.149:27804/pnfs/ndgf.org/data/dteam/tpc/domatest/file9_832a22cb-e61d-4776-b1ba-573721fb4ca8?dcache-http-uuid=fe4bd3df-3d8f-49c1-8f72-8a830016dc0a]   \n",
       "258  TRANSFER ERROR: Copy failed with mode 3rd push, with error: Transfer failed: failure: verification failed: failed to connect to server:｟*｠: Read timed out                                                                                                                                                                                                 \n",
       "259  TRANSFER globus_ftp_client: the server responded with an error 530 530-Login incorrect. : globus_gss_assist: Gridmap｟*｠ failure: Could not map /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=cmsrucio/CN=430796/CN=Robot: CMS Rucio Data Transfer 530- 530 End.                                                                                              \n",
       "281  DESTINATION SRM_PUTDONE Error on the surl srm:/lcg-lrz-srm.grid.lrz.de/pnfs/｟*｠/data/atlas/dq2/atlasdatadisk/rucio/tests/9b/46/ESD.4f5dd4be865c4842ac60661f5dea1c58 while putdone : [SE][PutDone][SRM_INVALID_PATH] No such file or directory: /pnfs/｟*｠/data/atlas/dq2/atlasdatadisk/rucio/tests/9b/46                                                    \n",
       "\n",
       "                                                                                                                                                                                                                           indices  \\\n",
       "151  [372822, 62752, 127534, 245582, 326861, 326862, 356450, 423298, 517856, 602046, 628326, 97186, 97339, 127954, 162337, 322490, 322501, 389078, 389344, 428354, 428491, 547868, 589335, 678740, 685320, 692718, 697973, 372460]   \n",
       "153  [351287, 143296, 251613, 657498, 657516, 539240, 356062, 356073, 656942, 288424, 523188, 412903, 563786, 651595, 177875, 584269, 639959, 61588, 317714, 397335, 397353, 631311, 248440, 539263, 607077, 217650]                 \n",
       "154  [64601, 84287, 103443, 104897, 104947, 122504, 140794, 172848, 174014, 193086, 236732, 244520, 251075, 311722, 319463, 368972, 373854, 398063, 443320, 562760, 564532, 572995, 598557, 612724]                                  \n",
       "155  [252606, 297310, 303922, 139774, 32751, 545306, 216602, 278783, 149347, 527711, 631097, 527712, 590115, 601910, 198774, 276209, 40812, 229111, 179348, 401451, 48035, 529526, 191457, 454507]                                   \n",
       "156  [157162, 110992, 297177, 578505, 386389, 168976, 558468, 358786, 314758, 225297, 237404, 180602, 48813, 119686, 119689, 636855, 196105, 197381, 467373, 89336, 568706, 568473]                                                  \n",
       "..                                                                                                                                                                              ...                                                  \n",
       "256  [409055]                                                                                                                                                                                                                        \n",
       "257  [172962]                                                                                                                                                                                                                        \n",
       "258  [215148]                                                                                                                                                                                                                        \n",
       "259  [305061]                                                                                                                                                                                                                        \n",
       "281  [126165]                                                                                                                                                                                                                        \n",
       "\n",
       "     cluster_size  \n",
       "151  28            \n",
       "153  26            \n",
       "154  24            \n",
       "155  24            \n",
       "156  22            \n",
       "..   ..            \n",
       "256  1             \n",
       "257  1             \n",
       "258  1             \n",
       "259  1             \n",
       "281  1             \n",
       "\n",
       "[130 rows x 3 columns]"
      ]
     },
     "execution_count": 71,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "clusters, outliers = cluster.split_clusters(cluster.result, 'cluster_size', threshold=30)\n",
    "outliers #clusters containing fewer than 3 messages"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 72,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>cluster_name</th>\n",
       "      <th>cluster_size</th>\n",
       "      <th>pattern</th>\n",
       "      <th>mean_similarity</th>\n",
       "      <th>std_similarity</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>100544</td>\n",
       "      <td>err: Communication error on send, err: [SE][][] httpg:/:/srm/: CGSI-gSOAP running on reports:</td>\n",
       "      <td>0.72</td>\n",
       "      <td>0.07</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>60088</td>\n",
       "      <td>Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: []</td>\n",
       "      <td>0.99</td>\n",
       "      <td>0.05</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>2</td>\n",
       "      <td>7</td>\n",
       "      <td>45044</td>\n",
       "      <td>Protocol not supported or path/url invalid: root:/:1094//atlasscratchdisk/rucio/tests///</td>\n",
       "      <td>0.62</td>\n",
       "      <td>0.05</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>3</td>\n",
       "      <td>2</td>\n",
       "      <td>29732</td>\n",
       "      <td>Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [4003] Authentication to:1094 failed; all protocols have been tried.</td>\n",
       "      <td>0.88</td>\n",
       "      <td>0.03</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>4</td>\n",
       "      <td>3</td>\n",
       "      <td>29278</td>\n",
       "      <td>: the server responded with an error 500 500-Command failed : System error in: No such file or directory 500-A system call failed: No such file or directory 500 End.</td>\n",
       "      <td>0.94</td>\n",
       "      <td>0.02</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>5</td>\n",
       "      <td>4</td>\n",
       "      <td>27037</td>\n",
       "      <td>Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [] Unable to ////;</td>\n",
       "      <td>0.81</td>\n",
       "      <td>0.03</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>6</td>\n",
       "      <td>5</td>\n",
       "      <td>26537</td>\n",
       "      <td>Destination file exists and overwrite is not enabled</td>\n",
       "      <td>1.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>7</td>\n",
       "      <td>6</td>\n",
       "      <td>24267</td>\n",
       "      <td>｟*｠: Unable to connect to:2811｟*｠: System error in connect: Connection timed out｟*｠: A system call failed: Connection timed out</td>\n",
       "      <td>0.89</td>\n",
       "      <td>0.03</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>8</td>\n",
       "      <td>8</td>\n",
       "      <td>19802</td>\n",
       "      <td>Error reported from srm_ifce : 2 [SE][Ls][SRM_INVALID_PATH] No such file or directory</td>\n",
       "      <td>0.99</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>9</td>\n",
       "      <td>9</td>\n",
       "      <td>18333</td>\n",
       "      <td>end-of-file was reached｟*｠: An end of file occurred</td>\n",
       "      <td>1.00</td>\n",
       "      <td>0.01</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>10</td>\n",
       "      <td>11</td>\n",
       "      <td>18207</td>\n",
       "      <td>[gfalt_copy_file][perform_copy][gfal_xrootd_3rd_copy][gfal_xrootd_3rd_copy_bulk] Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: []</td>\n",
       "      <td>0.99</td>\n",
       "      <td>0.03</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>11</td>\n",
       "      <td>10</td>\n",
       "      <td>17760</td>\n",
       "      <td>SOURCE SRM_GET_TURL error on the turl request : [SE][][SRM_FILE_UNAVAILABLE] File is.</td>\n",
       "      <td>1.00</td>\n",
       "      <td>0.02</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>12</td>\n",
       "      <td>12</td>\n",
       "      <td>16797</td>\n",
       "      <td>TRANSFER Transfer canceled because the gsiftp performance marker timeout of 360 seconds has been exceeded, or all performance markers during that period indicated zero bytes transferred</td>\n",
       "      <td>1.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>13</td>\n",
       "      <td>13</td>\n",
       "      <td>15173</td>\n",
       "      <td>on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Unable to open /dpm/nipne.ro/home/atlas/atlasscratchdisk/rucio/tests///; no delegated credentials for tpc</td>\n",
       "      <td>0.85</td>\n",
       "      <td>0.04</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>14</td>\n",
       "      <td>17</td>\n",
       "      <td>13091</td>\n",
       "      <td>: the server responded with an error 421 Service busy: Connection limit exceeded. Please try again later. Closing control connection.</td>\n",
       "      <td>0.98</td>\n",
       "      <td>0.04</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>15</td>\n",
       "      <td>14</td>\n",
       "      <td>12666</td>\n",
       "      <td>: the server responded with an error 530 530-globus_xio: Authentication Error 530-OpenSSL Error: s3_srvr.c:: in library: SSL routines, function: certificate 530-globus_gsi_callback_module: Could not verify credential 530-globus_gsi_callback_module: The certificate: with subject: /=/=/OU=/CN=/CN=/CN=/CN=/CN=</td>\n",
       "      <td>0.86</td>\n",
       "      <td>0.01</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>16</td>\n",
       "      <td>15</td>\n",
       "      <td>11878</td>\n",
       "      <td>Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Access denied: /pnfs/triumf.ca/data/atlas/atlasscratchdisk/rucio/tests///</td>\n",
       "      <td>0.83</td>\n",
       "      <td>0.01</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>17</td>\n",
       "      <td>16</td>\n",
       "      <td>11777</td>\n",
       "      <td>DESTINATION｟*｠ Connection timed out</td>\n",
       "      <td>1.00</td>\n",
       "      <td>0.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>18</td>\n",
       "      <td>23</td>\n",
       "      <td>11284</td>\n",
       "      <td>on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3012] sync - TPC open failed for src_url=root:/://atlasscratchdisk/rucio/tests///?fst.readahead=true</td>\n",
       "      <td>0.75</td>\n",
       "      <td>0.04</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>19</td>\n",
       "      <td>18</td>\n",
       "      <td>10277</td>\n",
       "      <td>TRANSFER globus_ftp_client: the server responded with an error 500 Command failed. : open/create : [ERROR] Server responded with an error: [3021] Unable to get quota space - quota not defined or exhausted /eos/cms/store/user/bmarzocc//94X_mc2017-RunIIFall18/////; Disk quota</td>\n",
       "      <td>0.93</td>\n",
       "      <td>0.03</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    cluster_name  cluster_size  \\\n",
       "0   0             100544         \n",
       "1   1             60088          \n",
       "2   7             45044          \n",
       "3   2             29732          \n",
       "4   3             29278          \n",
       "5   4             27037          \n",
       "6   5             26537          \n",
       "7   6             24267          \n",
       "8   8             19802          \n",
       "9   9             18333          \n",
       "10  11            18207          \n",
       "11  10            17760          \n",
       "12  12            16797          \n",
       "13  13            15173          \n",
       "14  17            13091          \n",
       "15  14            12666          \n",
       "16  15            11878          \n",
       "17  16            11777          \n",
       "18  23            11284          \n",
       "19  18            10277          \n",
       "\n",
       "                                                                                                                                                                                                                                                                                                                 pattern  \\\n",
       "0   err: Communication error on send, err: [SE][][] httpg:/:/srm/: CGSI-gSOAP running on reports:                                                                                                                                                                                                                          \n",
       "1   Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: []                                                                                                                                                                                                                                           \n",
       "2   Protocol not supported or path/url invalid: root:/:1094//atlasscratchdisk/rucio/tests///                                                                                                                                                                                                                               \n",
       "3   Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [4003] Authentication to:1094 failed; all protocols have been tried.                                                                                                                                                                         \n",
       "4   : the server responded with an error 500 500-Command failed : System error in: No such file or directory 500-A system call failed: No such file or directory 500 End.                                                                                                                                                  \n",
       "5   Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [] Unable to ////;                                                                                                                                                                                                                           \n",
       "6   Destination file exists and overwrite is not enabled                                                                                                                                                                                                                                                                   \n",
       "7   ｟*｠: Unable to connect to:2811｟*｠: System error in connect: Connection timed out｟*｠: A system call failed: Connection timed out                                                                                                                                                                                        \n",
       "8   Error reported from srm_ifce : 2 [SE][Ls][SRM_INVALID_PATH] No such file or directory                                                                                                                                                                                                                                  \n",
       "9   end-of-file was reached｟*｠: An end of file occurred                                                                                                                                                                                                                                                                    \n",
       "10  [gfalt_copy_file][perform_copy][gfal_xrootd_3rd_copy][gfal_xrootd_3rd_copy_bulk] Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: []                                                                                                                                                          \n",
       "11  SOURCE SRM_GET_TURL error on the turl request : [SE][][SRM_FILE_UNAVAILABLE] File is.                                                                                                                                                                                                                                  \n",
       "12  TRANSFER Transfer canceled because the gsiftp performance marker timeout of 360 seconds has been exceeded, or all performance markers during that period indicated zero bytes transferred                                                                                                                              \n",
       "13  on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Unable to open /dpm/nipne.ro/home/atlas/atlasscratchdisk/rucio/tests///; no delegated credentials for tpc                                                                                                                                   \n",
       "14  : the server responded with an error 421 Service busy: Connection limit exceeded. Please try again later. Closing control connection.                                                                                                                                                                                  \n",
       "15  : the server responded with an error 530 530-globus_xio: Authentication Error 530-OpenSSL Error: s3_srvr.c:: in library: SSL routines, function: certificate 530-globus_gsi_callback_module: Could not verify credential 530-globus_gsi_callback_module: The certificate: with subject: /=/=/OU=/CN=/CN=/CN=/CN=/CN=   \n",
       "16  Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3010] Access denied: /pnfs/triumf.ca/data/atlas/atlasscratchdisk/rucio/tests///                                                                                                                                                             \n",
       "17  DESTINATION｟*｠ Connection timed out                                                                                                                                                                                                                                                                                    \n",
       "18  on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3012] sync - TPC open failed for src_url=root:/://atlasscratchdisk/rucio/tests///?fst.readahead=true                                                                                                                                              \n",
       "19  TRANSFER globus_ftp_client: the server responded with an error 500 Command failed. : open/create : [ERROR] Server responded with an error: [3021] Unable to get quota space - quota not defined or exhausted /eos/cms/store/user/bmarzocc//94X_mc2017-RunIIFall18/////; Disk quota                                     \n",
       "\n",
       "    mean_similarity  std_similarity  \n",
       "0   0.72             0.07            \n",
       "1   0.99             0.05            \n",
       "2   0.62             0.05            \n",
       "3   0.88             0.03            \n",
       "4   0.94             0.02            \n",
       "5   0.81             0.03            \n",
       "6   1.00             0.00            \n",
       "7   0.89             0.03            \n",
       "8   0.99             0.00            \n",
       "9   1.00             0.01            \n",
       "10  0.99             0.03            \n",
       "11  1.00             0.02            \n",
       "12  1.00             0.00            \n",
       "13  0.85             0.04            \n",
       "14  0.98             0.04            \n",
       "15  0.86             0.01            \n",
       "16  0.83             0.01            \n",
       "17  1.00             0.00            \n",
       "18  0.75             0.04            \n",
       "19  0.93             0.03            "
      ]
     },
     "execution_count": 72,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "top_clusters = cluster.validation(clusters).sort_values(by=[\"cluster_size\"], ascending=False) #clusters sorted by similarity inside the cluster\n",
    "top_clusters.head(20)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 73,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "73.85057103667853\n",
      "99.88842220469195\n"
     ]
    }
   ],
   "source": [
    "print(top_clusters['cluster_size'].head(20).sum()/(df.shape[0]-1)*100)\n",
    "print(clusters['cluster_size'].sum()/(df.shape[0]-1)*100)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'tokenization': 312.1122,\n",
       " 'group_equals': 32.4067,\n",
       " 'tokens_vectorization': 2.877,\n",
       " 'sentence_vectorization': 4.1105,\n",
       " 'ml_clusterization': 6.6765,\n",
       " 'matching_clusterization': 0.7153,\n",
       " 'process': 358.9012,\n",
       " 'validation': 8.6354}"
      ]
     },
     "execution_count": 49,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "cluster.timings"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "top_clusters['pattern'].to_csv(\"patterns.txt\",index=False, header=True)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
